#!/bin/sh

picom -b

if [ -s "$XDG_CONFIG_HOME"/wallpapers.list ]; then
  hsetroot -full "$(shuf -n1 $XDG_CONFIG_HOME/wallpapers.list 2>/dev/null)"
else
  hsetroot -solid "#202020"
fi

tint2 &
lxqt-notificationd &
