#!/bin/sh

# -- check for root --
if [ "`id -u`" != "0" ]; then
  echo "ports.sh: sorry, this must be done as root." 1>&2
  exit 1
fi


# -- init_port_options(port_option_dirname, port_name, port_version) --
init_port_options()
{
  port_option_dirname="$1"
  port_name="$2"
  port_version="$3"
  port_complete_options_list=""
  port_options=""
}


# -- add_port_option(option_string) --
add_port_option()
{
  local option_string="$1"
  local option_name="${option_string#??? }"
  local option_state="${option_string%% $option_name}"
  
  port_complete_options_list="${port_complete_options_list} ${option_name}"
  if [ "$option_state" = "[x]" -o "$option_state" = "(*)" ]; then
    port_options="${port_options} OPTIONS_FILE_SET+=${option_name}"
  else
    port_options="${port_options} OPTIONS_FILE_UNSET+=${option_name}"
  fi
}


# -- create_port_options() --
create_port_options()
{
  if [ ! -e /usr/local/db/ports/"$port_option_dirname" ]; then
    mkdir -m 755 /usr/local/db/ports/"$port_option_dirname" || exit 1
  fi
  
  port_options_newline=`echo "${port_options# }" | tr ' ' '\n'`
  
  cat << EOF > /usr/local/db/ports/"$port_option_dirname"/options || exit 1
# This file is auto-generated by 'make config'.
# Options for ${port_name}-${port_version}
_OPTIONS_READ=${port_name}-${port_version}
_FILE_COMPLETE_OPTIONS_LIST=${port_complete_options_list# }
${port_options_newline}
EOF
}


# -- archivers/gtar OPTIONS --
init_port_options "archivers_gtar" "gtar" "1.28_1"
add_port_option "[ ] NLS"
add_port_option "[ ] STATIC"
create_port_options


# -- archivers/unzip OPTIONS --
init_port_options "archivers_unzip" "unzip" "6.0_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] ICONV"
add_port_option "( ) CHINESE"
add_port_option "( ) KOREAN"
add_port_option "( ) RUSSIAN"
create_port_options


# -- audio/flac --
init_port_options "audio_flac" "flac" "1.3.0"
add_port_option "[ ] DOCS"
add_port_option "[x] ICONV"
create_port_options


# -- audio/fluidsynth OPTIONS --
init_port_options "audio_fluidsynth" "fluidsynth" "1.1.6"
add_port_option "[ ] ALSA"
add_port_option "[ ] DBUS"
add_port_option "[ ] JACK"
add_port_option "[ ] LADSPA"
add_port_option "[ ] LASH"
add_port_option "[ ] PORTAUDIO"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SNDFILE"
create_port_options


# -- audio/lame --
init_port_options "audio_lame" "lame" "3.99.5_2"
add_port_option "[ ] DOCS"
create_port_options


# -- audio/libao OPTIONS --
init_port_options "audio_libao" "libao" "1.1.0_1"
add_port_option "[ ] ARTS"
add_port_option "[ ] DOCS"
add_port_option "[ ] ESOUND"
add_port_option "[ ] NAS"
add_port_option "[ ] PULSEAUDIO"
create_port_options


# -- audio/libogg --
init_port_options "audio_libogg" "libogg" "1.3.1,4"
add_port_option "[ ] DOCS"
create_port_options


# -- audio/libvorbis --
init_port_options "audio_libvorbis" "libvorbis" "1.3.3_1,3"
add_port_option "[ ] DOCS"
create_port_options


# -- audio/vorbis-tools --
init_port_options "audio_vorbis-tools" "vorbis-tools" "1.4.0_6,3"
add_port_option "[ ] NLS"
create_port_options


# -- converters/libiconv OPTIONS --
init_port_options "converters_libiconv" "libiconv" "1.14_3"
add_port_option "[ ] DOCS"
add_port_option "[x] ENCODINGS"
add_port_option "[ ] PATCHES"
create_port_options


# -- databases/ldb OPTIONS --
init_port_options "databases_ldb" "ldb" "1.1.17"
add_port_option "[ ] MANPAGES"
create_port_options


# -- databases/ntdb OPTIONS --
init_port_options "databases_ntdb" "ntdb" "1.0"
add_port_option "[ ] MANPAGES"
create_port_options


# -- databases/sqlite3 OPTIONS --
init_port_options "databases_sqlite3" "sqlite3" "3.8.8"
add_port_option "[ ] ARMOR"
add_port_option "[ ] DIRECT_READ"
add_port_option "[ ] EXTENSION"
add_port_option "[x] FTS4"
add_port_option "[ ] MEMMAN"
add_port_option "[x] METADATA"
add_port_option "[x] READLINE"
add_port_option "[x] SECURE_DELETE"
add_port_option "[ ] SOUNDEX"
add_port_option "[ ] STMT"
add_port_option "[x] THREADS"
add_port_option "[x] UNLOCK_NOTIFY"
add_port_option "[ ] UPD_DEL_LIMIT"
add_port_option "[ ] URI"
add_port_option "[ ] URI_AUTHORITY"
add_port_option "[ ] ICU"
add_port_option "[ ] UNICODE61"
add_port_option "[ ] RTREE"
add_port_option "[ ] RTREE_INT"
add_port_option "( ) TS0"
add_port_option "(*) TS1"
add_port_option "( ) TS2"
add_port_option "( ) TS3"
add_port_option "( ) STAT3"
add_port_option "( ) STAT4"
create_port_options


# -- databases/tdb OPTIONS --
init_port_options "databases_tdb" "tdb" "1.2.13,1"
add_port_option "[ ] MANPAGES"
create_port_options


# -- deskutils/parcellite OPTIONS --
init_port_options "deskutils_parcellite" "parcellite" "1.1.7,1"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- devel/apr1 OPTIONS --
init_port_options "devel_apr1" "apr" "1.5.1.1.5.4"
add_port_option "[x] IPV6"
add_port_option "[x] DEVRANDOM"
add_port_option "[ ] BDB"
add_port_option "[ ] GDBM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MYSQL"
add_port_option "[ ] NDBM"
add_port_option "[ ] PGSQL"
add_port_option "[ ] SQLITE"
add_port_option "[ ] FREETDS"
add_port_option "(*) SSL"
add_port_option "( ) NSS"
create_port_options


# -- devel/binutils OPTIONS --
init_port_options "devel_binutils" "binutils" "2.23.2"
add_port_option "[ ] NLS"
create_port_options


# -- devel/bison OPTIONS --
init_port_options "devel_bison" "bison" "2.7.1,1"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] NLS"
create_port_options


# -- devel/boehm-gc OPTIONS --
init_port_options "devel_boehm-gc" "boehm-gc" "7.2e"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/boost-libs OPTIONS --
init_port_options "devel_boost-libs" "boost-libs" "1.48.0"
add_port_option "[ ] DEBUG"
add_port_option "[x] ICU"
add_port_option "[ ] OPTIMIZED_CFLAGS"
add_port_option "[ ] VERBOSE_BUILD"
create_port_options


# -- devel/cmake OPTIONS --
init_port_options "devel_cmake" "cmake" "3.1.3"
add_port_option "[ ] DOCS"
add_port_option "[x] MANPAGES"
create_port_options


# -- devel/dbus OPTIONS --
init_port_options "devel_dbus" "dbus" "1.8.0"
add_port_option "[ ] MANPAGES"
add_port_option "[x] X11"
create_port_options


# -- devel/gamin OPTIONS --
init_port_options "devel_gamin" "gamin" "0.1.10_5"
add_port_option "[ ] GAM_POLLER"
add_port_option "[ ] LIBINOTIFY"
add_port_option "[x] RUN_AS_EUID"
create_port_options


# -- devel/gettext-tools OPTIONS --
init_port_options "devel_gettext-tools" "gettext-tools" "0.19.3"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/geany OPTIONS --
init_port_options "devel_geany" "geany" "1.23.1_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
add_port_option "[ ] VTE"
create_port_options


# -- devel/git OPTIONS --
init_port_options "devel_git" "git" "1.8.3.1"
add_port_option "[ ] CONTRIB"
add_port_option "[x] CURL"
add_port_option "[ ] CVS"
add_port_option "[ ] ETCSHELLS"
add_port_option "[x] GITWEB"
add_port_option "[ ] GUI"
add_port_option "[ ] HTMLDOCS"
add_port_option "[x] ICONV"
add_port_option "[ ] NLS"
add_port_option "[ ] P4"
add_port_option "[x] PERL"
add_port_option "[ ] SVN"
create_port_options


# -- devel/glib20 OPTIONS --
init_port_options "devel_glib20" "glib" "2.42.0"
add_port_option "[ ] COLLATION_FIX"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GDB"
create_port_options


# -- devel/gmake OPTIONS --
init_port_options "devel_gmake" "gmake" "3.82_1"
add_port_option "[ ] NLS"
create_port_options


# -- devel/gnulib OPTIONS --
init_port_options "devel_gnulib" "gnulib" "20140202"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/icu OPTIONS --
init_port_options "devel_icu" "icu" "50.1.2"
add_port_option "[x] THREADS"
create_port_options


# -- devel/kBuild OPTIONS --
init_port_options "devel_kBuild" "kBuild" "0.1.9998_2"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/libatomic_ops OPTIONS --
init_port_options "devel_libatomic_ops" "libatomic_ops" "7.4.0_1"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/libcheck OPTIONS --
init_port_options "devel_libcheck" "libcheck" "0.9.10"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
create_port_options


# -- devel/libdevq OPTIONS --
init_port_options "devel_libdevq" "libdevq" "0.0.2"
add_port_option "[ ] PROGRAMS"
create_port_options


# -- devel/libffi OPTIONS --
init_port_options "devel_libffi" "libffi" "3.0.13"
add_port_option "[ ] TESTS"
create_port_options


# -- devel/libglade2 OPTIONS --
init_port_options "devel_libglade2" "libglade2" "2.6.4_5"
add_port_option "[x] PYTHON"
create_port_options


# -- devel/libsigc++20 OPTIONS --
init_port_options "devel_libsigc++20" "libsigc++" "2.4.0"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/llvm35 OPTIONS --
init_port_options "devel_llvm35" "llvm35" "3.5.1"
add_port_option "[ ] ASSERTS"
add_port_option "[ ] CMAKE"
add_port_option "[ ] DOCS"
add_port_option "[x] LIT"
add_port_option "[ ] LTOPLUGIN"
add_port_option "[x] MANPAGES"
create_port_options


# -- devel/m4 OPTIONS --
init_port_options "devel_m4" "m4" "1.4.17_1,1"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBSIGSEGV"
create_port_options


# -- devel/mercurial OPTIONS --
init_port_options "devel_mercurial" "mercurial" "3.0.2"
add_port_option "[ ] CA_BUNDLE"
add_port_option "[x] DATA"
add_port_option "[ ] DOCS"
add_port_option "[x] EXAMPLES"
add_port_option "[ ] FREEBSD"
add_port_option "[ ] NLS"
create_port_options


# -- devel/nasm --
init_port_options "devel_nasm" "nasm" "2.11.05,1"
add_port_option "[ ] DOCS"
add_port_option "[x] RDOFF"
create_port_options


# -- devel/ninja --
init_port_options "devel_ninja" "ninja" "1.5.1,1"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/pcre OPTIONS --
init_port_options "devel_pcre" "pcre" "8.34"
add_port_option "[ ] DOCS"
add_port_option "[ ] LIBEDIT"
add_port_option "[ ] READLINE"
add_port_option "[x] STACK_RECURSION"
create_port_options


# -- devel/popt OPTIONS --
init_port_options "devel_popt" "popt" "1.16"
add_port_option "[ ] NLS"
create_port_options


# -- devel/py-babel OPTIONS --
init_port_options "devel_py-babel" "py27-Babel" "1.3_2"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/py-Jinja2 OPTIONS --
init_port_options "devel_py-Jinja2" "py27-Jinja2" "2.7.3"
add_port_option "[x] BABEL"
add_port_option "[ ] EXAMPLES"
create_port_options


# -- devel/subversion OPTIONS --
init_port_options "devel_subversion" "subversion" "1.8.9_7"
add_port_option "[ ] BDB"
add_port_option "[ ] DOCS"
add_port_option "[x] FREEBSD_TEMPLATE"
add_port_option "[ ] MAINTAINER_DEBUG"
add_port_option "[ ] NLS"
add_port_option "[x] P4_STYLE_MARKERS"
add_port_option "[ ] SASL"
add_port_option "[ ] SERF"
add_port_option "[ ] STATIC"
add_port_option "[ ] SVNSERVE_WRAPPER"
add_port_option "[ ] TEST"
add_port_option "[ ] TOOLS"
create_port_options


# -- devel/talloc OPTIONS --
init_port_options "devel_talloc" "talloc" "2.1.0"
add_port_option "[ ] MANPAGES"
create_port_options


# -- devel/tevent OPTIONS --
init_port_options "devel_tevent" "tevent" "0.9.21"
add_port_option "[ ] MANPAGES"
create_port_options


# -- devel/uthash OPTIONS --
init_port_options "devel_uthash" "uthash" "1.9.8p2"
add_port_option "[ ] DOCS"
create_port_options


# -- devel/yasm OPTIONS --
init_port_options "devel_yasm" "yasm" "1.2.0"
add_port_option "[ ] NLS"
create_port_options


# -- dns/adns OPTIONS --
init_port_options "dns_adns" "adns" "1.4_2"
add_port_option "[ ] DOCS"
create_port_options


# -- dns/libidn OPTIONS --
init_port_options "dns_libidn" "libidn" "1.28"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- dns/py-dnspython --
init_port_options "dns_py-dnspython" "py27-dnspython" "1.12.0"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] PYCRYPTO"
create_port_options


# -- editors/leafpad OPTIONS --
init_port_options "editors_leafpad" "leafpad" "0.8.18.1_1"
add_port_option "[ ] NLS"
create_port_options


# -- editors/nano OPTIONS --
init_port_options "editors_nano" "nano" "2.2.6"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- emulators/virtualbox-ose-additions OPTIONS --
init_port_options "emulators_virtualbox-ose-additions" "virtualbox-ose-additions" "4.2.14"
add_port_option "[ ] DEBUG"
add_port_option "[x] OPENGL"
add_port_option "[x] X11"
create_port_options


# -- ftp/curl OPTIONS --
init_port_options "ftp_curl" "curl" "7.40.0"
add_port_option "[x] CA_BUNDLE"
add_port_option "[ ] COOKIES"
add_port_option "[ ] CURL_DEBUG"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] HTTP2"
add_port_option "[ ] IDN"
add_port_option "[x] IPV6"
add_port_option "[ ] LDAP"
add_port_option "[ ] LDAPS"
add_port_option "[ ] LIBSSH2"
add_port_option "[x] PROXY"
add_port_option "[ ] RTMP"
add_port_option "[x] TLS_SRP"
add_port_option "( ) GSSAPI_BASE"
add_port_option "( ) HEIMDAL_PORT"
add_port_option "( ) KRB5_PORT"
add_port_option "( ) CARES"
add_port_option "(*) THREADED_RESOLVER"
add_port_option "( ) CYASSL"
add_port_option "( ) GNUTLS"
add_port_option "( ) NSS"
add_port_option "(*) OPENSSL"
add_port_option "( ) POLARSSL"
create_port_options


# -- ftp/wget OPTIONS --
init_port_options "ftp_wget" "wget" "1.14_2"
add_port_option "[ ] IDN"
add_port_option "[x] IPV6"
add_port_option "[ ] NLS"
add_port_option "[ ] PCRE"
add_port_option "( ) GNUTLS"
add_port_option "(*) OPENSSL"
create_port_options


# -- graphics/autotrace OPTIONS --
init_port_options "graphics_autotrace" "autotrace" "0.31.1_23"
add_port_option "[x] IMAGEMAGICK"
add_port_option "[ ] MING"
add_port_option "[ ] PSTOEDIT"
create_port_options


# -- graphics/cairo OPTIONS --
init_port_options "graphics_cairo" "cairo" "1.10.2_5,2"
add_port_option "[x] GLIB"
add_port_option "[ ] OPENGL"
add_port_option "[x] X11"
add_port_option "[x] XCB"
create_port_options


# -- graphics/cairomm OPTIONS --
init_port_options "graphics_cairomm" "cairomm" "1.10.0_2"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/colord OPTIONS --
init_port_options "graphics_colord" "colord" "1.0.1_3"
add_port_option "[ ] MANPAGES"
create_port_options


# -- graphics/dri OPTIONS --
init_port_options "graphics_dri" "dri" "9.1.7_6,2"
add_port_option "[x] GALLIUM"
add_port_option "[ ] TEXTURE"
add_port_option "[x] VDPAU"
create_port_options


# -- graphics/gdk-pixbuf2 OPTIONS --
init_port_options "graphics_gdk-pixbuf2" "gdk-pixbuf2" "2.26.5_3"
add_port_option "[x] JASPER"
add_port_option "[x] JPEG"
add_port_option "[x] PNG"
add_port_option "[x] TIFF"
create_port_options


# -- graphics/gegl OPTIONS --
init_port_options "graphics_gegl" "gegl" "0.2.0_10"
add_port_option "[x] CAIRO"
add_port_option "[ ] DOCS"
add_port_option "[ ] ENSCRIPT"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] EXIV2"
add_port_option "[ ] FFMPEG"
add_port_option "[ ] GRAPHVIZ"
add_port_option "[x] JASPER"
add_port_option "[x] JPEG"
add_port_option "[x] LIBRSVG2"
add_port_option "[x] LUA"
add_port_option "[ ] OPENEXR"
add_port_option "[ ] OPENRAW"
add_port_option "[x] PANGO"
add_port_option "[x] PIXBUF"
add_port_option "[x] PNG"
add_port_option "[ ] SDL"
add_port_option "[x] SIMD"
add_port_option "[ ] SPIRO"
add_port_option "[ ] V4L"
create_port_options


# -- graphics/giblib --
init_port_options "graphics_giblib" "giblib" "1.2.4_11"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/giflib OPTIONS --
init_port_options "graphics_giflib" "giflib-nox11" "4.2.3"
add_port_option "[ ] DOCBOOK"
add_port_option "[ ] DOCS"
add_port_option "[ ] X11"
create_port_options


# -- graphics/gimp OPTIONS --
init_port_options "graphics_gimp" "gimp" "2.8.6,2"
add_port_option "[ ] HELP"
add_port_option "[ ] PRINT"
add_port_option "[ ] PYTHON"
create_port_options


# -- graphics/gimp-app OPTIONS --
init_port_options "graphics_gimp-app" "gimp-app" "2.8.6,1"
add_port_option "[ ] AA"
add_port_option "[x] DBUS"
add_port_option "[ ] GHOSTSCRIPT"
add_port_option "[ ] GVFS"
add_port_option "[ ] HELPBROWSER"
add_port_option "[x] JASPER"
add_port_option "[x] LIBEXIF"
add_port_option "[ ] LIBMNG"
add_port_option "[x] LIBRSVG2"
add_port_option "[x] POPPLER"
add_port_option "[x] SIMD"
add_port_option "[ ] WMF"
create_port_options


# -- graphics/gpicview OPTIONS --
init_port_options "graphics_gpicview" "gpicview" "0.2.3"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- graphics/ImageMagick OPTIONS --
init_port_options "graphics_ImageMagick" "ImageMagick" "6.8.9.8_3,1"
add_port_option "[x] BZIP2"
add_port_option "[ ] DJVU"
add_port_option "[ ] DOCS"
add_port_option "[ ] FFTW"
add_port_option "[x] FONTCONFIG"
add_port_option "[ ] FPX"
add_port_option "[ ] FREETYPE"
add_port_option "[ ] GRAPHVIZ"
add_port_option "[ ] GSLIB"
add_port_option "[x] JBIG"
add_port_option "[x] JPEG"
add_port_option "[x] JPEG2000"
add_port_option "[x] LCMS2"
add_port_option "[x] LQR"
add_port_option "[x] LZMA"
add_port_option "[ ] MODULES"
add_port_option "[ ] OPENEXR"
add_port_option "[ ] OPENMP"
add_port_option "[ ] PANGO"
add_port_option "[ ] PDF"
add_port_option "[x] PERL"
add_port_option "[x] PNG"
add_port_option "[ ] SIMD"
add_port_option "[ ] SVG"
add_port_option "[ ] TESTS"
add_port_option "[ ] THREADS"
add_port_option "[x] TIFF"
add_port_option "[x] WEBP"
add_port_option "[ ] WMF"
add_port_option "[ ] X11"
add_port_option "[x] 16BIT_PIXEL"
add_port_option "[ ] HDRI"
create_port_options


# -- graphics/imlib2 OPTIONS --
init_port_options "graphics_imlib2" "imlib2" "1.4.5_2,2"
add_port_option "[ ] GIF"
add_port_option "[ ] ID3"
add_port_option "[x] JPEG"
add_port_option "[x] PNG"
add_port_option "[x] TIFF"
add_port_option "[x] X11"
create_port_options


# -- graphics/inkscape OPTIONS --
init_port_options "graphics_inkscape" "inkscape" "0.91"
add_port_option "[ ] CDR"
add_port_option "[ ] DBUS"
add_port_option "[ ] OPENMP"
add_port_option "[x] POPPLER"
add_port_option "[ ] VISIO"
add_port_option "[ ] WPG"
create_port_options


# -- graphics/jasper OPTIONS --
init_port_options "graphics_jasper" "jasper" "1.900.1_14"
add_port_option "[ ] DOCS"
add_port_option "[ ] OPENGL"
add_port_option "[ ] UUID"
create_port_options


# -- graphics/jbigkit OPTIONS --
init_port_options "graphics_jbigkit" "jbigkit" "2.1_1"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/jpeg OPTIONS --
init_port_options "graphics_jpeg" "jpeg" "8_4"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/lcms OPTIONS --
init_port_options "graphics_lcms" "lcms" "1.19_1,1"
add_port_option "[ ] DOCS"
add_port_option "[ ] JPEGICC"
add_port_option "[ ] TIFFICC"
create_port_options


# -- graphics/lcms2 OPTIONS --
init_port_options "graphics_lcms2" "lcms2" "2.4"
add_port_option "[ ] DOCS"
add_port_option "[ ] JPEGICC"
add_port_option "[ ] TIFFICC"
create_port_options


# -- graphics/libdrm OPTIONS --
init_port_options "graphics_libdrm" "libdrm" "2.4.17_1"
add_port_option "[ ] MANPAGES"
create_port_options


# -- graphics/libexif OPTIONS --
init_port_options "graphics_libexif" "libexif" "0.6.21"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- graphics/liblqr-1 OPTIONS --
init_port_options "graphics_liblqr-1" "liblqr-1" "0.4.1_8"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] HTMLDOCS"
create_port_options


# -- graphics/libwpg OPTIONS --
init_port_options "graphics_libwpg" "libwpg" "0.2.2"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/openjpeg15 OPTIONS --
init_port_options "graphics_openjpeg15" "openjpeg15" "1.5.2"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/p5-Image-ExifTool OPTIONS --
init_port_options "graphics_p5-Image-ExifTool" "p5-Image-ExifTool" "9.27"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/png OPTIONS --
init_port_options "graphics_png" "png" "1.5.18"
add_port_option "[ ] APNG"
add_port_option "[ ] PNGTEST"
create_port_options


# -- graphics/poppler OPTIONS --
init_port_options "graphics_poppler" "poppler" "0.26.3"
add_port_option "[x] CAIRO"
add_port_option "[ ] CURL"
add_port_option "[x] OPENJPEG"
create_port_options


# -- graphics/tiff OPTIONS --
init_port_options "graphics_tiff" "tiff" "4.0.3_4"
add_port_option "[ ] DOCS"
create_port_options


# -- graphics/webp OPTIONS --
init_port_options "graphics_webp" "webp" "0.3.1_4"
add_port_option "[ ] X11"
create_port_options


# -- lang/gcc OPTIONS --
init_port_options "lang_gcc" "gcc" "4.6.3"
add_port_option "[x] BOOTSTRAP"
add_port_option "[ ] JAVA"
create_port_options


# -- lang/perl5.18 OPTIONS --
init_port_options "lang_perl5.18" "perl5" "5.18.4_5"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GDBM"
add_port_option "[x] MULTIPLICITY"
add_port_option "[x] PERL_64BITINT"
add_port_option "[x] PTHREAD"
add_port_option "[ ] SITECUSTOMIZE"
add_port_option "[x] USE_PERL"
add_port_option "(*) THREADS"
add_port_option "( ) PERL_MALLOC"
create_port_options


# -- lang/python27 OPTIONS --
init_port_options "lang_python27" "python27" "2.7.8_6"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[ ] SEM"
add_port_option "[x] THREADS"
add_port_option "( ) UCS2"
add_port_option "(*) UCS4"
create_port_options


# -- lang/python34 OPTIONS --
init_port_options "lang_python34" "python34" "3.4.2_1"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[x] THREADS"
add_port_option "[ ] TSC"
add_port_option "( ) FNV"
add_port_option "( ) SIPHASH"
create_port_options


# -- math/gmp OPTIONS --
init_port_options "math_gmp" "gmp" "5.1.3_1"
add_port_option "[ ] CPU_OPTS"
create_port_options


# -- misc/help2man OPTIONS --
init_port_options "misc_help2man" "help2man" "1.43.2"
add_port_option "[ ] NLS"
create_port_options


# -- multimedia/libkate OPTIONS --
init_port_options "multimedia_libkate" "libkate" "0.4.1_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] DOXYGEN"
add_port_option "[ ] HTMLDOCS"
add_port_option "[ ] KATEDJ"
create_port_options


# -- multimedia/libvdpau OPTIONS --
init_port_options "multimedia_libvdpau" "libvdpau" "0.8_1"
add_port_option "[ ] DEBUG"
create_port_options


# -- multimedia/xvid OPTIONS --
init_port_options "multimedia_xvid" "xvid" "1.3.2,1"
add_port_option "[x] OPTIMIZED_CFLAGS"
create_port_options


# -- net/openldap24-client OPTIONS --
init_port_options "net_openldap24-client" "openldap-client" "2.4.39"
add_port_option "[ ] FETCH"
add_port_option "[ ] GSSAPI"
create_port_options


# -- net/samba41 OPTIONS --
init_port_options "net_samba41" "samba41" "4.1.16"
add_port_option "[ ] ACL_SUPPORT"
add_port_option "[ ] ADS"
add_port_option "[ ] AD_DC"
add_port_option "[x] AIO_SUPPORT"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DEVELOPER"
add_port_option "[ ] DNSUPDATE"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXP_MODULES"
add_port_option "[ ] FAM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MANPAGES"
add_port_option "[ ] PAM_SMBPASS"
add_port_option "[x] PTHREADPOOL"
add_port_option "[ ] QUOTAS"
add_port_option "[ ] SYSLOG"
add_port_option "[ ] UTMP"
add_port_option "( ) NSUPDATE"
add_port_option "( ) BIND99"
add_port_option "( ) BIND910"
add_port_option "( ) AVAHI"
add_port_option "( ) MDNSRESPONDER"
create_port_options


# -- net/wireshark OPTIONS --
init_port_options "net_wireshark" "wireshark" "1.12.3"
add_port_option "[x] ADNS"
add_port_option "[ ] CARES"
add_port_option "[ ] GCRYPT"
add_port_option "[ ] GEOIP"
add_port_option "[ ] GNUTLS"
add_port_option "[ ] GSSAPI"
add_port_option "[x] IPV6"
add_port_option "[ ] LUA"
add_port_option "[x] PCRE"
add_port_option "[ ] RTP"
add_port_option "[ ] SNMP"
add_port_option "[ ] THREADS"
add_port_option "[x] X11"
add_port_option "(*) GTK3"
add_port_option "( ) QT5"
create_port_options


# -- ports-mgmt/portmaster OPTIONS --
init_port_options "ports-mgmt_portmaster" "portmaster" "3.17"
add_port_option "[ ] BASH"
add_port_option "[ ] ZSH"
create_port_options


# -- print/freetype2 OPTIONS --
init_port_options "print_freetype2" "freetype2" "2.5.0.1"
add_port_option "[ ] LCD_FILTERING"
add_port_option "[ ] PNG"
create_port_options


# -- print/fontforge OPTIONS --
init_port_options "print_fontforge" "fontforge" "20120731.b_2"
add_port_option "[ ] CAIRO"
add_port_option "[x] DOCS"
add_port_option "[ ] FREETYPE"
add_port_option "[x] MULTILAYER"
add_port_option "[ ] PANGO"
add_port_option "[x] PLUGINS"
add_port_option "[ ] PYTHON"
create_port_options


# -- print/texinfo OPTIONS --
init_port_options "print_texinfo" "texinfo" "5.2.20150101"
add_port_option "[ ] NLS"
create_port_options


# -- security/ca_root_nss OPTIONS --
init_port_options "security_ca_root_nss" "ca_root_nss" "3.15.5"
add_port_option "[ ] ETCSYMLINK"
create_port_options


# -- security/gnutls OPTIONS --
init_port_options "security_gnutls" "gnutls" "3.2.16_3"
add_port_option "[x] CRYWRAP"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBDANE"
add_port_option "[ ] NLS"
add_port_option "[x] P11KIT"
add_port_option "[x] TPM"
add_port_option "[x] ZLIB"
create_port_options


# -- security/libgcrypt OPTIONS --
init_port_options "security_libgcrypt" "libgcrypt" "1.5.3_3"
add_port_option "[ ] DOCS"
create_port_options


# -- security/libgpg-error OPTIONS --
init_port_options "security_libgpg-error" "libgpg-error" "1.12"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- security/libtasn1 OPTIONS --
init_port_options "security_libtasn1" "libtasn1" "3.3"
add_port_option "[ ] DOCS"
create_port_options


# -- security/nettle OPTIONS --
init_port_options "security_nettle" "nettle" "2.7.1"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
create_port_options


# -- security/p5-Authen-SASL OPTIONS --
init_port_options "security_p5-Authen-SASL" "p5-Authen-SASL" "2.16"
add_port_option "[ ] KERBEROS"
create_port_options


# -- security/p5-IO-Socket-SSL OPTIONS --
init_port_options "security_p5-IO-Socket-SSL" "p5-IO-Socket-SSL" "1.94"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] IDN"
add_port_option "[ ] IPV6"
create_port_options


# -- security/p5-Net-SSLeay OPTIONS --
init_port_options "security_p5-Net-SSLeay" "p5-Net-SSLeay" "1.55"
add_port_option "[ ] EXAMPLES"
create_port_options


# -- security/trousers OPTIONS --
init_port_options "security_trousers" "trousers-tddl" "0.3.10_7"
add_port_option "[ ] DEBUG"
add_port_option "[ ] EMULATOR"
create_port_options


# -- sysutils/cdrtools OPTIONS --
init_port_options "sysutils_cdrtools" "cdrtools" "3.00_2"
add_port_option "[ ] CDDA2MP3"
add_port_option "[ ] CDDA2OGG"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
add_port_option "[ ] RSCSI"
create_port_options


# -- sysutils/dmidecode OPTIONS --
init_port_options "sysutils_dmidecode" "dmidecode" "2.12"
add_port_option "[ ] DOCS"
create_port_options


# -- sysutils/polkit OPTIONS --
init_port_options "sysutils_polkit" "polkit" "0.105_1"
add_port_option "[ ] MANPAGES"
create_port_options


# -- textproc/aspell OPTIONS --
init_port_options "textproc_aspell" "aspell" "0.60.6.1_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] ISPELL"
add_port_option "[x] NLS"
create_port_options


# -- textproc/enchant OPTIONS --
init_port_options "textproc_enchant" "enchant" "1.6.0_1"
add_port_option "[x] ASPELL"
add_port_option "[ ] HSPELL"
add_port_option "[ ] HUNSPELL"
add_port_option "[ ] ISPELL"
add_port_option "[ ] ZEMBEREK"
create_port_options


# -- textproc/flex OPTIONS --
init_port_options "textproc_flex" "flex" "2.5.37_1"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- textproc/gsed OPTIONS --
init_port_options "textproc_gsed" "gsed" "4.2.2"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- textproc/libxml2 OPTIONS --
init_port_options "textproc_libxml2" "libxml2" "2.8.0_2"
add_port_option "[ ] MEM_DEBUG"
add_port_option "[x] SCHEMA"
add_port_option "[x] THREADS"
add_port_option "[ ] THREAD_ALLOC"
add_port_option "[ ] XMLLINT_HIST"
create_port_options


# -- textproc/libxslt OPTIONS --
init_port_options "textproc_libxslt" "libxslt" "1.1.28_1"
add_port_option "[x] CRYPTO"
add_port_option "[ ] MEM_DEBUG"
create_port_options


# -- textproc/p5-XML-SAX OPTIONS --
init_port_options "textproc_p5-XML-SAX" "p5-XML-SAX" "0.99"
add_port_option "[ ] WRITE_INI_OK"
create_port_options


# -- textproc/py-docutils OPTIONS --
init_port_options "textproc_py-docutils" "py27-docutils" "0.12"
add_port_option "[ ] PYGMENTS"
create_port_options


# -- textproc/py-pygments OPTIONS --
init_port_options "textproc_py-pygments" "py27-pygments" "1.6_2"
add_port_option "[ ] DOCS"
create_port_options


# -- textproc/xmlcatmgr --
init_port_options "textproc_xmlcatmgr" "xmlcatmgr" "2.2"
add_port_option "[ ] DOCS"
create_port_options


# -- www/p5-libwww OPTIONS --
init_port_options "www_p5-libwww" "p5-libwww" "6.05"
add_port_option "[ ] HTTPS"
create_port_options


# -- www/tidy-devel OPTIONS --
init_port_options "www_tidy-devel" "tidy-devel" "090315.c_2"
add_port_option "[ ] DOCS"
create_port_options


# -- x11/babl OPTIONS --
init_port_options "x11_babl" "babl" "0.1.10"
add_port_option "[x] SIMD"
create_port_options


# -- x11/gmrun OPTIONS --
init_port_options "x11_gmrun" "gmrun" "0.9.2_10"
add_port_option "[ ] DOCS"
create_port_options


# -- x11/libfm OPTIONS --
init_port_options "x11_libfm" "libfm" "1.2.1"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
add_port_option "[ ] STATIC"
create_port_options


# -- x11/libxcb OPTIONS --
init_port_options "x11_libxcb" "libxcb" "1.10_2"
add_port_option "[ ] DOCS"
create_port_options


# -- x11/lxrandr OPTIONS --
init_port_options "x11_lxrandr" "lxrandr" "0.1.2"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- x11/pixman OPTIONS --
init_port_options "x11_pixman" "pixman" "0.30.0"
add_port_option "[x] SIMD"
create_port_options


# -- x11/tint OPTIONS --
init_port_options "x11_tint" "tint2" "0.11_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] PYCONF"
create_port_options


# -- x11/xkeyboard-config OPTIONS --
init_port_options "x11_xkeyboard-config" "xkeyboard-config" "2.9_1"
add_port_option "[ ] ETERSOFT"
create_port_options


# -- x11/xterm OPTIONS --
init_port_options "x11_xterm" "xterm" "312"
add_port_option "[x] 256COLOR"
add_port_option "[ ] DABBREV"
add_port_option "[ ] DECTERM"
add_port_option "[ ] GNOME"
add_port_option "[ ] LOGGING"
add_port_option "[ ] LUIT"
add_port_option "[ ] PCRE"
add_port_option "[ ] SIXEL"
add_port_option "[x] WCHAR"
add_port_option "( ) XAW3D"
add_port_option "( ) XAW3DXFT"
add_port_option "( ) NEXTAW"
create_port_options


# -- x11-fm/pcmanfm OPTIONS --
init_port_options "x11-fm_pcmanfm" "pcmanfm" "1.2.0"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- x11-fonts/dejavu OPTIONS --
init_port_options "x11-fonts_dejavu" "dejavu" "2.33"
add_port_option "[ ] DOCS"
add_port_option "[ ] LINKS"
create_port_options


# -- x11-fonts/fontconfig OPTIONS --
init_port_options "x11-fonts_fontconfig" "fontconfig" "2.11.0_3,1"
add_port_option "[ ] DOCS"
create_port_options


# -- x11-fonts/junicode OPTIONS --
init_port_options "x11-fonts_junicode" "junicode" "0.7.6_1"
add_port_option "[ ] DOCS"
create_port_options


# -- x11-servers/xorg-server OPTIONS --
init_port_options "x11-servers_xorg-server" "xorg-server" "1.7.7_10,1"
add_port_option "[x] AIGLX"
add_port_option "[x] SUID"
add_port_option "( ) HAL"
add_port_option "(*) DEVD"
create_port_options


# -- x11-themes/gtk-engines2 OPTIONS --
init_port_options "x11-themes_gtk-engines2" "gtk-engines2" "2.20.2_1"
add_port_option "[ ] ANIMATION"
create_port_options


# -- x11-themes/gtk-murrine-engine OPTIONS --
init_port_options "x11-themes_gtk-murrine-engine" "gtk-murrine-engine" "0.98.2"
add_port_option "[ ] ANIMATION"
create_port_options


# -- x11-themes/lxappearance OPTIONS --
init_port_options "x11-themes_lxappearance" "lxappearance" "0.5.2_1"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- x11-toolkits/gtk20 OPTIONS --
init_port_options "x11-toolkits_gtk20" "gtk" "2.24.19"
add_port_option "[x] COLORD"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
create_port_options


# -- x11-toolkits/gtk30 OPTIONS --
init_port_options "x11-toolkits_gtk30" "gtk3" "3.14.7"
add_port_option "[ ] CLOUDPRINT"
add_port_option "[x] COLORD"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
create_port_options


# -- x11-toolkits/pango OPTIONS --
init_port_options "x11-toolkits_pango" "pango" "1.30.1"
add_port_option "[x] X11"
create_port_options


# -- x11-wm/obconf OPTIONS --
init_port_options "x11-wm_obconf" "obconf" "2.0.4"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- x11-wm/openbox OPTIONS --
init_port_options "x11-wm_openbox" "openbox" "3.5.2_5"
add_port_option "[x] IMLIB"
add_port_option "[ ] NLS"
add_port_option "[x] NOTIFY"
add_port_option "[x] PANGO"
add_port_option "[x] SVG"
create_port_options
