#!/bin/sh

# -- check for root --
if [ "`id -u`" != "0" ]; then
  echo "ports.sh: sorry, this must be done as root." 1>&2
  exit 1
fi


# -- init_port_options(port_option_dirname, port_name, port_version) --
init_port_options()
{
  port_option_dirname="$1"
  port_name="$2"
  port_version="$3"
  port_complete_options_list=""
  port_options=""
}


# -- add_port_option(option_string) --
add_port_option()
{
  local option_string="$1"
  local option_name="${option_string#??? }"
  local option_state="${option_string%% $option_name}"
  
  port_complete_options_list="${port_complete_options_list} ${option_name}"
  if [ "$option_state" = "[x]" -o "$option_state" = "(*)" ]; then
    port_options="${port_options} OPTIONS_FILE_SET+=${option_name}"
  else
    port_options="${port_options} OPTIONS_FILE_UNSET+=${option_name}"
  fi
}


# -- create_port_options() --
create_port_options()
{
  if [ ! -e /usr/local/db/ports/"$port_option_dirname" ]; then
    mkdir -m 755 /usr/local/db/ports/"$port_option_dirname" || exit 1
  fi
  
  port_options_newline=`echo "${port_options# }" | tr ' ' '\n'`
  
  cat << EOF > /usr/local/db/ports/"$port_option_dirname"/options || exit 1
# This file is auto-generated by 'make config'.
# Options for ${port_name}-${port_version}
_OPTIONS_READ=${port_name}-${port_version}
_FILE_COMPLETE_OPTIONS_LIST=${port_complete_options_list# }
${port_options_newline}
EOF
}


# -- archivers/libarchive2 OPTIONS --
init_port_options "archivers_libarchive" "libarchive" "3.1.2_4,1"
add_port_option "[x] LZO"
add_port_option "[ ] NETTLE"
create_port_options


# -- archivers/lzo2 OPTIONS --
init_port_options "archivers_lzo2" "lzo2" "2.09"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
create_port_options


# -- benchmarks/iperf OPTIONS --
init_port_options "benchmarks_iperf" "iperf" "2.0.5"
add_port_option "[ ] DOCS"
add_port_option "[x] IPV6"
add_port_option "[x] THREADS"
create_port_options


# -- databases/ldb OPTIONS --
init_port_options "databases_ldb" "ldb" "1.1.17"
add_port_option "[ ] MANPAGES"
create_port_options


# -- databases/tdb OPTIONS --
init_port_options "databases_tdb" "tdb" "1.2.13,1"
add_port_option "[ ] MANPAGES"
create_port_options


# -- devel/gmake OPTIONS --
init_port_options "devel_gmake" "gmake" "3.82_1"
add_port_option "[ ] NLS"
create_port_options


# -- devel/libevent2 OPTIONS --
init_port_options "devel_libevent2" "libevent2" "2.0.21"
add_port_option "[x] OPENSSL"
add_port_option "[x] THREADS"
create_port_options


# -- devel/libffi OPTIONS --
init_port_options "devel_libffi" "libffi" "3.0.13"
add_port_option "[ ] TESTS"
create_port_options


# -- devel/m4 OPTIONS --
init_port_options "devel_m4" "m4" "1.4.17_1,1"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBSIGSEGV"
create_port_options


# -- devel/popt OPTIONS --
init_port_options "devel_popt" "popt" "1.16"
add_port_option "[ ] NLS"
create_port_options


# -- devel/talloc OPTIONS --
init_port_options "devel_talloc" "talloc" "2.1.0"
add_port_option "[ ] MANPAGES"
create_port_options


# -- devel/tevent OPTIONS --
init_port_options "devel_tevent" "tevent" "0.9.21"
add_port_option "[ ] MANPAGES"
create_port_options


# -- dns/libidn OPTIONS --
init_port_options "dns_libidn" "libidn" "1.28"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- dns/py-dnspython --
init_port_options "dns_py-dnspython" "py27-dnspython" "1.12.0"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] PYCRYPTO"
create_port_options


# -- editors/nano OPTIONS --
init_port_options "editors_nano" "nano" "2.4.0"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] NLS"
create_port_options


# -- lang/perl5.20 OPTIONS --
init_port_options "lang_perl5.20" "perl5" "5.20.2_4"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GDBM"
add_port_option "[x] MULTIPLICITY"
add_port_option "[x] PERL_64BITINT"
add_port_option "[x] PTHREAD"
add_port_option "[ ] SITECUSTOMIZE"
add_port_option "(*) THREADS"
add_port_option "( ) PERL_MALLOC"
create_port_options


# -- lang/python27 OPTIONS --
init_port_options "lang_python27" "python27" "2.7.8_6"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[x] SEM"
add_port_option "[x] THREADS"
add_port_option "( ) UCS2"
add_port_option "(*) UCS4"
create_port_options


# -- math/gmp OPTIONS --
init_port_options "math_gmp" "gmp" "5.1.3_1"
add_port_option "[ ] CPU_OPTS"
create_port_options


# -- net/openldap24-client OPTIONS --
init_port_options "net_openldap24-client" "openldap-client" "2.4.40_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] FETCH"
add_port_option "[ ] GSSAPI"
create_port_options


# -- net/samba43 OPTIONS --
init_port_options "net_samba43" "samba43" "4.3.1"
add_port_option "[ ] ACL_SUPPORT"
add_port_option "[ ] ADS"
add_port_option "[ ] AD_DC"
add_port_option "[x] AIO_SUPPORT"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DEVELOPER"
add_port_option "[ ] DNSUPDATE"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXP_MODULES"
add_port_option "[ ] FAM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MANPAGES"
add_port_option "[ ] PAM_SMBPASS"
add_port_option "[x] PTHREADPOOL"
add_port_option "[ ] QUOTAS"
add_port_option "[ ] SYSLOG"
add_port_option "[ ] UTMP"
add_port_option "( ) NSUPDATE"
add_port_option "( ) BIND99"
add_port_option "( ) BIND910"
add_port_option "( ) AVAHI"
add_port_option "( ) MDNSRESPONDER"
create_port_options


# -- ports-mgmt/portmaster OPTIONS --
init_port_options "ports-mgmt_portmaster" "portmaster" "3.17"
add_port_option "[ ] BASH"
add_port_option "[ ] ZSH"
create_port_options


# -- security/ca_root_nss OPTIONS --
init_port_options "security_ca_root_nss" "ca_root_nss" "3.15.5"
add_port_option "[ ] ETCSYMLINK"
create_port_options


# -- security/gnutls OPTIONS --
init_port_options "security_gnutls" "gnutls" "3.4.10"
add_port_option "[x] CRYWRAP"
add_port_option "[ ] DANE"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] IDN"
add_port_option "[ ] NLS"
add_port_option "[x] P11KIT"
add_port_option "[x] TPM"
add_port_option "[x] ZLIB"
create_port_options


# -- security/libgcrypt OPTIONS --
init_port_options "security_libgcrypt" "libgcrypt" "1.5.3_3"
add_port_option "[ ] DOCS"
create_port_options


# -- security/libgpg-error OPTIONS --
init_port_options "security_libgpg-error" "libgpg-error" "1.12"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
create_port_options


# -- security/libtasn1 OPTIONS --
init_port_options "security_libtasn1" "libtasn1" "3.3"
add_port_option "[ ] DOCS"
create_port_options


# -- security/nettle OPTIONS --
init_port_options "security_nettle" "nettle" "2.7.1"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
create_port_options


# -- security/trousers OPTIONS --
init_port_options "security_trousers" "trousers-tddl" "0.3.10_7"
add_port_option "[ ] DEBUG"
add_port_option "[ ] EMULATOR"
create_port_options


# -- shells/zsh OPTIONS --
init_port_options "shells_zsh" "zsh" "5.0.7_3"
add_port_option "[ ] DEBUG"
add_port_option "[x] DOCS"
add_port_option "[x] EXAMPLES"
add_port_option "[ ] GDBM"
add_port_option "[ ] MAILDIR"
add_port_option "[ ] MEM"
add_port_option "[ ] PCRE"
add_port_option "[x] SECURE_FREE"
add_port_option "[ ] STATIC"
create_port_options


# -- sysutils/dmidecode OPTIONS --
init_port_options "sysutils_dmidecode" "dmidecode" "2.12"
add_port_option "[ ] DOCS"
create_port_options


# -- sysutils/smartmontools OPTIONS --
init_port_options "sysutils_smartmontools" "smartmontools" "6.2_1"
add_port_option "[ ] DOCS"
create_port_options


# -- sysutils/tmux OPTIONS --
init_port_options "sysutils_tmux" "tmux" "1.9a"
add_port_option "[ ] BACKSPACE"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBEVENT_STATIC"
create_port_options


