#!/bin/sh

# -- check for root --
if [ "`id -u`" != "0" ]; then
  echo "write_ports_options.sh: sorry, this must be done as root." 1>&2
  exit 1
fi


# -- init_port_options(port_option_dirname, port_name, port_version) --
init_port_options()
{
  port_option_dirname="$1"
  port_name="$2"
  port_version="$3"
  port_complete_options_list=""
  port_options=""
}


# -- add_port_option(option_string) --
add_port_option()
{
  local option_string="$1"
  local option_name="${option_string#??? }"
  local option_state="${option_string%% $option_name}"
  
  port_complete_options_list="${port_complete_options_list} ${option_name}"
  if [ "$option_state" = "[x]" -o "$option_state" = "(*)" ]; then
    port_options="${port_options} OPTIONS_FILE_SET+=${option_name}"
  else
    port_options="${port_options} OPTIONS_FILE_UNSET+=${option_name}"
  fi
}


# -- create_port_options() --
create_port_options()
{
  if [ ! -e /usr/local/db/ports/"$port_option_dirname" ]; then
    mkdir -m 755 /usr/local/db/ports/"$port_option_dirname" || exit 1
  fi
  
  port_options_newline=`echo "${port_options# }" | tr ' ' '\n'`
  
  cat << EOF > /usr/local/db/ports/"$port_option_dirname"/options || exit 1
# This file is auto-generated by 'make config'.
# Options for ${port_name}-${port_version}
_OPTIONS_READ=${port_name}-${port_version}
_FILE_COMPLETE_OPTIONS_LIST=${port_complete_options_list# }
${port_options_newline}
EOF
}


# -- archivers/libarchive OPTIONS --
init_port_options "archivers_libarchive" "libarchive" "3.2.0_1,1"
add_port_option "[x] LZ4"
add_port_option "[x] LZO"
add_port_option "[ ] NETTLE"
create_port_options


# -- benchmarks/iperf OPTIONS --
init_port_options "benchmarks_iperf" "iperf" "2.0.5"
add_port_option "[ ] DOCS"
add_port_option "[x] IPV6"
add_port_option "[x] THREADS"
create_port_options


# -- converters/libiconv OPTIONS --
init_port_options "converters_libiconv" "libiconv" "1.14_3"
add_port_option "[ ] DOCS"
add_port_option "[x] ENCODINGS"
add_port_option "[ ] PATCHES"
create_port_options


# -- databases/ldb OPTIONS --
init_port_options "databases_ldb" "ldb" "1.1.17"
add_port_option "[ ] MANPAGES"
create_port_options


# -- databases/sqlite3 OPTIONS --
init_port_options "databases_sqlite3" "sqlite3" "3.17.0"
add_port_option "[ ] ARMOR"
add_port_option "[x] DBSTAT"
add_port_option "[ ] DIRECT_READ"
add_port_option "[ ] EXTENSION"
add_port_option "[ ] FTS3_TOKEN"
add_port_option "[x] FTS4"
add_port_option "[ ] FTS5"
add_port_option "[ ] JSON1"
add_port_option "[ ] LIKENOTBLOB"
add_port_option "[ ] MEMMAN"
add_port_option "[x] METADATA"
add_port_option "[ ] NULL_TRIM"
add_port_option "[ ] RBU"
add_port_option "[x] SECURE_DELETE"
add_port_option "[ ] SESSION"
add_port_option "[ ] SOUNDEX"
add_port_option "[ ] STMT"
add_port_option "[x] STSHELL"
add_port_option "[x] THREADS"
add_port_option "[ ] UNKNOWN_SQL"
add_port_option "[x] UNLOCK_NOTIFY"
add_port_option "[ ] UPD_DEL_LIMIT"
add_port_option "[ ] URI"
add_port_option "[ ] URI_AUTHORITY"
add_port_option "[ ] ICU"
add_port_option "[ ] UNICODE61"
add_port_option "[ ] RTREE"
add_port_option "[ ] RTREE_INT"
add_port_option "( ) READLINES"
add_port_option "( ) READLINEP"
add_port_option "( ) EDITLINE"
add_port_option "( ) TS0"
add_port_option "(*) TS1"
add_port_option "( ) TS2"
add_port_option "( ) TS3"
add_port_option "( ) STAT3"
add_port_option "( ) STAT4"
create_port_options


# -- databases/tdb OPTIONS --
init_port_options "databases_tdb" "tdb" "1.2.13,1"
add_port_option "[ ] MANPAGES"
create_port_options


# -- devel/apr1 OPTIONS --
init_port_options "devel_apr1" "apr" "1.5.2.1.5.4_2"
add_port_option "[x] IPV6"
add_port_option "[x] DEVRANDOM"
add_port_option "[ ] BDB"
add_port_option "[ ] GDBM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MYSQL"
add_port_option "[ ] NDBM"
add_port_option "[ ] PGSQL"
add_port_option "[ ] SQLITE"
add_port_option "[ ] FREETDS"
add_port_option "(*) SSL"
add_port_option "( ) NSS"
create_port_options


# -- devel/gdb OPTIONS --
init_port_options "devel_gdb" "gdb" "7.11.1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] EXPAT"
add_port_option "[x] GDB_LINK"
add_port_option "[ ] GUILE"
add_port_option "[x] KGDB"
add_port_option "[ ] PYTHON"
add_port_option "[x] TUI"
add_port_option "( ) BASE_READLINE"
add_port_option "( ) BUNDLED_READLINE"
add_port_option "(*) PORT_READLINE"
create_port_options


# -- devel/gettext-tools OPTIONS --
init_port_options "devel_gettext-tools" "gettext-tools" "0.19.5.1"
add_port_option "[ ] DOCS"
add_port_option "[x] THREADS"
create_port_options


# -- devel/git OPTIONS --
init_port_options "devel_git" "git" "2.11.0_3"
add_port_option "[ ] CONTRIB"
add_port_option "[x] CURL"
add_port_option "[ ] CVS"
add_port_option "[ ] GITWEB"
add_port_option "[ ] GUI"
add_port_option "[ ] HTMLDOCS"
add_port_option "[x] ICONV"
add_port_option "[ ] NLS"
add_port_option "[ ] P4"
add_port_option "[x] PCRE"
add_port_option "[x] PERL"
add_port_option "[ ] SEND_EMAIL"
add_port_option "[ ] SUBTREE"
add_port_option "[ ] SVN"
create_port_options


# -- devel/glib20 OPTIONS --
init_port_options "devel_glib20" "glib" "2.42.0"
add_port_option "[ ] COLLATION_FIX"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GDB"
create_port_options


# -- devel/libevent OPTIONS --
init_port_options "devel_libevent" "libevent" "2.1.8"
add_port_option "[x] OPENSSL"
add_port_option "[x] THREADS"
create_port_options


# -- devel/libffi OPTIONS --
init_port_options "devel_libffi" "libffi" "3.0.13"
add_port_option "[ ] TESTS"
create_port_options


# -- devel/m4 OPTIONS --
init_port_options "devel_m4" "m4" "1.4.17_1,1"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBSIGSEGV"
create_port_options


# -- devel/pcre OPTIONS --
init_port_options "devel_pcre" "pcre" "8.39"
add_port_option "[ ] DOCS"
add_port_option "[x] MAN3"
add_port_option "[x] STACK_RECURSION"
add_port_option "( ) LIBEDIT"
add_port_option "( ) READLINE"
create_port_options


# -- devel/readline OPTIONS --
init_port_options "devel_readline" "readline" "6.3.6_1"
add_port_option "[ ] DOCS"
add_port_option "[x] TERMCAP"
create_port_options


# -- devel/subversion OPTIONS --
init_port_options "devel_subversion" "subversion" "1.9.5"
add_port_option "[ ] BDB"
add_port_option "[ ] DOCS"
add_port_option "[x] FREEBSD_TEMPLATE"
add_port_option "[ ] MAINTAINER_DEBUG"
add_port_option "[ ] NLS"
add_port_option "[ ] SASL"
add_port_option "[x] SERF"
add_port_option "[ ] STATIC"
add_port_option "[ ] SVNSERVE_WRAPPER"
add_port_option "[ ] TEST"
add_port_option "[ ] TOOLS"
create_port_options


# -- devel/talloc OPTIONS --
init_port_options "devel_talloc" "talloc" "2.1.0"
add_port_option "[ ] MANPAGES"
create_port_options


# -- devel/tevent OPTIONS --
init_port_options "devel_tevent" "tevent" "0.9.21"
add_port_option "[ ] MANPAGES"
create_port_options


# -- dns/dnsmasq OPTIONS --
init_port_options "dns_dnsmasq" "dnsmasq" "2.76,1"
add_port_option "[ ] DBUS"
add_port_option "[ ] DNSSEC"
add_port_option "[ ] DOCS"
add_port_option "[ ] IPSET"
add_port_option "[x] IPV6"
add_port_option "[ ] LUA"
add_port_option "( ) IDN"
add_port_option "( ) NLS"
create_port_options


# -- dns/py-dnspython OPTIONS --
init_port_options "dns_py-dnspython" "py27-dnspython" "1.12.0"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] PYCRYPTO"
create_port_options


# -- ftp/curl OPTIONS --
init_port_options "ftp_curl" "curl" "7.51.0_1"
add_port_option "[x] CA_BUNDLE"
add_port_option "[x] COOKIES"
add_port_option "[ ] CURL_DEBUG"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] HTTP2"
add_port_option "[ ] IDN"
add_port_option "[x] IPV6"
add_port_option "[ ] LDAP"
add_port_option "[ ] LDAPS"
add_port_option "[ ] LIBSSH2"
add_port_option "[ ] METALINK"
add_port_option "[x] PROXY"
add_port_option "[ ] PSL"
add_port_option "[ ] RTMP"
add_port_option "[ ] SMB"
add_port_option "[x] TLS_SRP"
add_port_option "( ) GSSAPI_BASE"
add_port_option "( ) GSSAPI_HEIMDAL"
add_port_option "( ) GSSAPI_MIT"
add_port_option "(*) GSSAPI_NONE"
add_port_option "( ) CARES"
add_port_option "(*) THREADED_RESOLVER"
add_port_option "( ) GNUTLS"
add_port_option "( ) NSS"
add_port_option "(*) OPENSSL"
add_port_option "( ) POLARSSL"
add_port_option "( ) WOLFSSL"
create_port_options


# -- lang/perl5.24 OPTIONS --
init_port_options "lang_perl5.24" "perl5" "5.24.1.r4_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DTRACE"
add_port_option "[ ] GDBM"
add_port_option "[x] MULTIPLICITY"
add_port_option "[x] PERL_64BITINT"
add_port_option "[x] PTHREAD"
add_port_option "[ ] SITECUSTOMIZE"
add_port_option "(*) THREADS"
add_port_option "( ) PERL_MALLOC"
create_port_options


# -- lang/python27 OPTIONS --
init_port_options "lang_python27" "python27" "2.7.8_6"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[x] SEM"
add_port_option "[x] THREADS"
add_port_option "( ) UCS2"
add_port_option "(*) UCS4"
create_port_options


# -- lang/python35 OPTIONS --
init_port_options "lang_python35" "python35" "3.5.2"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[x] THREADS"
add_port_option "[ ] TSC"
add_port_option "( ) FNV"
add_port_option "( ) SIPHASH"
create_port_options


# -- math/gmp OPTIONS --
init_port_options "math_gmp" "gmp" "5.1.3_1"
add_port_option "[ ] CPU_OPTS"
create_port_options


# -- net/miniupnpd OPTIONS --
init_port_options "net_miniupnpd" "miniupnpd" "1.9.20160113,1"
add_port_option "[ ] CHECK_PORTINUSE"
add_port_option "[x] IPV6"
add_port_option "[ ] LEASEFILE"
add_port_option "[x] PF_FILTER_RULES"
add_port_option "[ ] UPNP_IGDV2"
add_port_option "[ ] UPNP_STRICT"
create_port_options


# -- net/mpd5 OPTIONS --
init_port_options "net_mpd5" "mpd" "5.7"
add_port_option "[ ] NG_IPACCT"
create_port_options


# -- net/openldap24-client OPTIONS --
init_port_options "net_openldap24-client" "openldap-client" "2.4.40_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] FETCH"
add_port_option "[ ] GSSAPI"
create_port_options


# -- net/samba46 OPTIONS --
init_port_options "net_samba46" "samba46" "4.6.1_1"
add_port_option "[ ] ADS"
add_port_option "[ ] AD_DC"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DEVELOPER"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXP_MODULES"
add_port_option "[ ] FAM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MANPAGES"
add_port_option "[ ] NTVFS"
add_port_option "[ ] QUOTAS"
add_port_option "[ ] SYSLOG"
add_port_option "[ ] UTMP"
add_port_option "( ) NSUPDATE"
add_port_option "( ) BIND99"
add_port_option "( ) BIND910"
add_port_option "( ) BIND911"
add_port_option "( ) AVAHI"
add_port_option "( ) MDNSRESPONDER"
create_port_options


# -- ports-mgmt/portmaster OPTIONS --
init_port_options "ports-mgmt_portmaster" "portmaster" "3.17"
add_port_option "[ ] BASH"
add_port_option "[ ] ZSH"
create_port_options


# -- security/ca_root_nss OPTIONS --
init_port_options "security_ca_root_nss" "ca_root_nss" "3.15.5"
add_port_option "[ ] ETCSYMLINK"
create_port_options


# -- security/gnutls OPTIONS --
init_port_options "security_gnutls" "gnutls" "3.4.10"
add_port_option "[x] CRYWRAP"
add_port_option "[ ] DANE"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] IDN"
add_port_option "[ ] NLS"
add_port_option "[x] P11KIT"
add_port_option "[ ] TPM"
add_port_option "[x] ZLIB"
create_port_options


# -- security/openvpn OPTIONS --
init_port_options "security_openvpn" "openvpn" "2.4.0"
add_port_option "[ ] DOCS"
add_port_option "[ ] EASYRSA"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] LZ4"
add_port_option "[ ] PKCS11"
add_port_option "[ ] SMALL"
add_port_option "[ ] TEST"
add_port_option "[ ] TUNNELBLICK"
add_port_option "[ ] X509ALTUSERNAME"
add_port_option "(*) OPENSSL"
add_port_option "( ) MBEDTLS"
create_port_options


# -- shells/zsh OPTIONS --
init_port_options "shells_zsh" "zsh" "5.2_2"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] ETCDIR"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] GDBM"
add_port_option "[ ] MEM"
add_port_option "[ ] PCRE"
add_port_option "[ ] STATIC"
create_port_options


# -- sysutils/tmux OPTIONS --
init_port_options "sysutils_tmux" "tmux" "2.3_2"
add_port_option "[ ] BACKSPACE"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBEVENT_STATIC"
create_port_options


# -- www/serf OPTIONS --
init_port_options "www_serf" "serf" "1.3.8_1"
add_port_option "[ ] DOCS"
add_port_option "( ) MIT"
add_port_option "( ) HEIMDAL"
add_port_option "( ) HEIMDAL_BASE"
create_port_options
