#!/bin/sh

# -- check for root --
if [ "`id -u`" != "0" ]; then
  echo "write_ports_options.sh: sorry, this must be done as root." 1>&2
  exit 1
fi


# -- init_port_options(port_option_dirname, port_name, port_version) --
init_port_options()
{
  port_option_dirname="$1"
  port_name="$2"
  port_version="$3"
  port_complete_options_list=""
  port_options=""
}


# -- add_port_option(option_string) --
add_port_option()
{
  local option_string="$1"
  local option_name="${option_string#??? }"
  local option_state="${option_string%% $option_name}"
  
  port_complete_options_list="${port_complete_options_list} ${option_name}"
  if [ "$option_state" = "[x]" -o "$option_state" = "(*)" ]; then
    port_options="${port_options} OPTIONS_FILE_SET+=${option_name}"
  else
    port_options="${port_options} OPTIONS_FILE_UNSET+=${option_name}"
  fi
}


# -- create_port_options() --
create_port_options()
{
  if [ ! -e /usr/local/db/ports/"$port_option_dirname" ]; then
    mkdir -m 755 /usr/local/db/ports/"$port_option_dirname" || exit 1
  fi
  
  port_options_newline=`echo "${port_options# }" | tr ' ' '\n'`
  
  cat << EOF > /usr/local/db/ports/"$port_option_dirname"/options || exit 1
# This file is auto-generated by 'make config'.
# Options for ${port_name}-${port_version}
_OPTIONS_READ=${port_name}-${port_version}
_FILE_COMPLETE_OPTIONS_LIST=${port_complete_options_list# }
${port_options_newline}
EOF
}


# -- OPTIONS --
init_port_options "archivers_libarchive" "libarchive" "3.2.0_1,1"
add_port_option "[x] LZ4"
add_port_option "[x] LZO"
add_port_option "[ ] NETTLE"
create_port_options


init_port_options "archivers_unrar" "unrar" "5.50b4,5"
add_port_option "[x] OPENSSL_AES"
create_port_options


init_port_options "archivers_unzip" "unzip" "6.0_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] ICONV"
add_port_option "( ) CHINESE"
add_port_option "( ) KOREAN"
add_port_option "( ) RUSSIAN"
create_port_options


init_port_options "audio_alsa-lib" "alsa-lib" "1.0.27.2"
add_port_option "[ ] PYTHON"
create_port_options


init_port_options "audio_alsa-plugins" "alsa-plugins" "1.0.27_2"
add_port_option "[ ] FFMPEG"
add_port_option "[ ] JACK"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SAMPLERATE"
add_port_option "[ ] SPEEX"
add_port_option "[x] IO_PTR"
add_port_option "[ ] BLKCNT_P2"
add_port_option "[x] BUFSZ_P2"
add_port_option "[ ] VERBOSE"
create_port_options


init_port_options "audio_audacity" "audacity" "2.1.2_5"
add_port_option "[ ] ALSA"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] DYNLOAD"
add_port_option "[ ] FFMPEG"
add_port_option "[x] FLAC"
add_port_option "[x] ID3TAG"
add_port_option "[ ] LADSPA"
add_port_option "[ ] LAME"
add_port_option "[ ] LV2"
add_port_option "[x] MAD"
add_port_option "[ ] NLS"
add_port_option "[x] SBSMS"
add_port_option "[x] SOUNDTOUCH"
add_port_option "[x] SSE"
add_port_option "[ ] TWOLAME"
add_port_option "[x] VAMP"
add_port_option "[x] VORBIS"
add_port_option "[x] VST"
create_port_options


init_port_options "audio_liba52" "liba52" "0.7.4_3"
add_port_option "[ ] DJBFFT"
add_port_option "[ ] DOCS"
add_port_option "[ ] OPTIMIZED_CFLAGS"
create_port_options


init_port_options "audio_libcanberra-gtk3" "libcanberra-gtk3" "0.30_4"
add_port_option "[ ] GSTREAMER"
add_port_option "[ ] PULSEAUDIO"
create_port_options


init_port_options "audio_libmad" "libmad" "0.15.1b_6"
add_port_option "[ ] SPEED"
create_port_options


init_port_options "audio_libsidplayfp" "libsidplayfp" "1.8.6"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] DOXYGEN"
add_port_option "[x] BHINTS"
add_port_option "[x] INLINE"
add_port_option "[ ] MMX"
create_port_options


init_port_options "audio_libsndfile" "libsndfile" "1.0.27"
add_port_option "[ ] CPU_CLIP"
add_port_option "[ ] DOCS"
add_port_option "[x] EXTERNAL"
create_port_options


init_port_options "audio_libsoxr" "libsoxr" "0.1.2.20160529_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] OPENMP"
add_port_option "[ ] SIMD"
add_port_option "( ) AVFFT"
add_port_option "( ) PFFFT"
create_port_options


init_port_options "audio_mpg123" "mpg123" "1.25.6"
add_port_option "[ ] SNDIO"
create_port_options


init_port_options "audio_openal-soft" "openal-soft" "1.18.0_1"
add_port_option "[ ] CONFIG"
add_port_option "[ ] FLUIDSYNTH"
add_port_option "[ ] JACK"
add_port_option "[x] OSS"
add_port_option "[ ] PORTAUDIO"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SNDIO"
create_port_options


init_port_options "audio_opusfile" "opusfile" "0.8"
add_port_option "[ ] DOCS"
add_port_option "[ ] DOXYGEN"
create_port_options


init_port_options "audio_sdl_sound" "sdl_sound" "1.0.3_13"
add_port_option "[x] FLAC"
add_port_option "[x] MIDI"
add_port_option "[ ] MIKMOD"
add_port_option "[ ] MODPLUG"
add_port_option "[ ] PHYSFS"
add_port_option "[ ] SMPEG"
add_port_option "[ ] SPEEX"
add_port_option "[x] VORBIS"
create_port_options


init_port_options "audio_soundtouch" "soundtouch" "1.9.0_1"
add_port_option "[ ] DOCS"
add_port_option "[ ] INTEGER_SAMPLES"
add_port_option "[ ] OPENMP"
add_port_option "[x] SSE"
create_port_options


init_port_options "audio_taglib" "taglib" "1.10"
add_port_option "[ ] RCC"
create_port_options


init_port_options "audio_timidity" "timidity" "0.2i_1"
add_port_option "(*) GOEMON"
add_port_option "( ) GUSPAT"
create_port_options


init_port_options "audio_wavpack" "wavpack" "5.1.0"
add_port_option "[x] ASM"
create_port_options


init_port_options "audio_wildmidi" "wildmidi" "0.4.0"
add_port_option "[x] PLAYER"
add_port_option "[ ] PLAYERSTATIC"
add_port_option "[ ] STATIC"
add_port_option "(*) ALSA"
add_port_option "( ) OPENAL"
add_port_option "( ) OSS"
create_port_options


init_port_options "benchmarks_iperf" "iperf" "2.0.5"
add_port_option "[ ] DOCS"
add_port_option "[x] IPV6"
add_port_option "[x] THREADS"
create_port_options


init_port_options "converters_libiconv" "libiconv" "1.14_3"
add_port_option "[ ] DOCS"
add_port_option "[x] ENCODINGS"
add_port_option "[ ] PATCHES"
create_port_options


init_port_options "databases_leveldb" "leveldb" "1.20_1"
add_port_option "[ ] GPERFTOOLS"
add_port_option "[x] SNAPPY"
create_port_options


init_port_options "databases_ldb" "ldb" "1.1.17"
add_port_option "[ ] MANPAGES"
create_port_options


init_port_options "databases_sqlite3" "sqlite3" "3.17.0"
add_port_option "[ ] ARMOR"
add_port_option "[x] DBSTAT"
add_port_option "[ ] DIRECT_READ"
add_port_option "[ ] EXTENSION"
add_port_option "[ ] FTS3_TOKEN"
add_port_option "[x] FTS4"
add_port_option "[ ] FTS5"
add_port_option "[ ] JSON1"
add_port_option "[ ] LIKENOTBLOB"
add_port_option "[ ] MEMMAN"
add_port_option "[x] METADATA"
add_port_option "[ ] NULL_TRIM"
add_port_option "[ ] RBU"
add_port_option "[x] SECURE_DELETE"
add_port_option "[ ] SESSION"
add_port_option "[ ] SOUNDEX"
add_port_option "[ ] STMT"
add_port_option "[x] STSHELL"
add_port_option "[x] THREADS"
add_port_option "[ ] UNKNOWN_SQL"
add_port_option "[x] UNLOCK_NOTIFY"
add_port_option "[ ] UPD_DEL_LIMIT"
add_port_option "[ ] URI"
add_port_option "[ ] URI_AUTHORITY"
add_port_option "[ ] ICU"
add_port_option "[ ] UNICODE61"
add_port_option "[ ] RTREE"
add_port_option "[ ] RTREE_INT"
add_port_option "( ) READLINES"
add_port_option "( ) READLINEP"
add_port_option "( ) EDITLINE"
add_port_option "( ) TS0"
add_port_option "(*) TS1"
add_port_option "( ) TS2"
add_port_option "( ) TS3"
add_port_option "( ) STAT3"
add_port_option "( ) STAT4"
create_port_options


init_port_options "databases_tdb" "tdb" "1.2.13,1"
add_port_option "[ ] MANPAGES"
create_port_options


init_port_options "deskutils_parcellite" "parcellite" "1.1.7,1"
add_port_option "[ ] DOCS"
add_port_option "[x] NLS"
create_port_options


init_port_options "deskutils_spice-gtk" "spice-gtk" "0.33"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
add_port_option "[ ] SASL"
add_port_option "(*) GSTREAMER"
add_port_option "( ) PULSEAUDIO"
add_port_option "( ) NOAUDIO"
create_port_options


init_port_options "devel_apr1" "apr" "1.6.2.1.6.0"
add_port_option "[x] DEVRANDOM"
add_port_option "[x] IPV6"
add_port_option "[ ] BDB"
add_port_option "[ ] GDBM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MYSQL"
add_port_option "[ ] NDBM"
add_port_option "[ ] ODBC"
add_port_option "[ ] PGSQL"
add_port_option "[ ] SQLITE"
add_port_option "[ ] FREETDS"
add_port_option "(*) SSL"
add_port_option "( ) NSS"
create_port_options


init_port_options "devel_arm-none-eabi-binutils" "arm-none-eabi-binutils" "2.27_5,1"
add_port_option "[ ] RELRO"
add_port_option "[ ] STATIC"
create_port_options


init_port_options "devel_binutils" "binutils" "2.27_5,1"
add_port_option "[ ] NLS"
add_port_option "[ ] RELRO"
add_port_option "[ ] STATIC"
create_port_options


init_port_options "devel_boehm-gc" "boehm-gc" "7.6.0"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
create_port_options


init_port_options "devel_boehm-gc-threaded" "boehm-gc-threaded" "7.6.0_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] PARALLEL_MARK"
create_port_options


init_port_options "devel_boost-libs" "boost-libs" "1.63.0_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] OPTIMIZED_CFLAGS"
add_port_option "[x] ICONV"
add_port_option "[x] ICU"
create_port_options


init_port_options "devel_cargo" "cargo" "0.15.0_2"
add_port_option "[x] BOOTSTRAP"
create_port_options


init_port_options "devel_cmake" "cmake" "3.6.2"
add_port_option "[ ] DOCS"
add_port_option "[x] MANPAGES"
create_port_options


init_port_options "devel_cppunit" "cppunit" "1.13.2"
add_port_option "[ ] DOCS"
add_port_option "[ ] DOXYGEN"
create_port_options


init_port_options "devel_cscope" "cscope" "15.8a"
add_port_option "[ ] XCSCOPE"
create_port_options


init_port_options "devel_dbus" "dbus" "1.8.0"
add_port_option "[ ] MANPAGES"
add_port_option "[x] X11"
create_port_options


init_port_options "devel_gconf2" "gconf2" "3.2.6_4"
add_port_option "[ ] DOCS"
add_port_option "[ ] LDAP"
create_port_options


init_port_options "devel_gdb" "gdb" "8.0_3"
add_port_option "[ ] DEBUG"
add_port_option "[x] GDB_LINK"
add_port_option "[ ] GUILE"
add_port_option "[x] KGDB"
add_port_option "[ ] PYTHON"
add_port_option "[x] TUI"
add_port_option "( ) BASE_READLINE"
add_port_option "( ) BUNDLED_READLINE"
add_port_option "(*) PORT_READLINE"
create_port_options


init_port_options "devel_geany" "geany" "1.23.1_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
add_port_option "[ ] VTE"
create_port_options


init_port_options "devel_gettext-tools" "gettext-tools" "0.19.5.1"
add_port_option "[ ] DOCS"
add_port_option "[x] THREADS"
create_port_options


init_port_options "devel_git" "git" "2.11.0_3"
add_port_option "[ ] CONTRIB"
add_port_option "[x] CURL"
add_port_option "[ ] CVS"
add_port_option "[ ] GITWEB"
add_port_option "[ ] GUI"
add_port_option "[ ] HTMLDOCS"
add_port_option "[x] ICONV"
add_port_option "[ ] NLS"
add_port_option "[ ] P4"
add_port_option "[x] PCRE"
add_port_option "[x] PERL"
add_port_option "[ ] SEND_EMAIL"
add_port_option "[ ] SUBTREE"
add_port_option "[ ] SVN"
create_port_options


init_port_options "devel_glib20" "glib" "2.42.0"
add_port_option "[ ] COLLATION_FIX"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GDB"
create_port_options


init_port_options "devel_icu" "icu" "50.1.2"
add_port_option "[x] THREADS"
create_port_options


init_port_options "devel_libdevq" "libdevq" "0.0.2"
add_port_option "[ ] PROGRAMS"
create_port_options


init_port_options "devel_libevent" "libevent" "2.1.8"
add_port_option "[x] OPENSSL"
add_port_option "[x] THREADS"
create_port_options


init_port_options "devel_libffi" "libffi" "3.0.13"
add_port_option "[ ] TESTS"
create_port_options


init_port_options "devel_libglade2" "libglade2" "2.6.4_5"
add_port_option "[x] PYTHON"
create_port_options


init_port_options "devel_libvirt" "libvirt" "3.2.0"
add_port_option "[x] BHYVE"
add_port_option "[ ] DOCS"
add_port_option "[ ] GNUTLS"
add_port_option "[ ] NLS"
add_port_option "[ ] NSS"
add_port_option "[x] QEMU"
add_port_option "[x] READLINE"
add_port_option "[ ] SASL"
add_port_option "[ ] XEN"
add_port_option "[ ] ZFS"
create_port_options


init_port_options "devel_libvirt-glib" "libvirt-glib" "1.0.0"
add_port_option "[ ] VALA"
create_port_options


init_port_options "devel_llvm40" "llvm40" "4.0.0_1"
add_port_option "[x] CLANG"
add_port_option "[x] COMPILER_RT"
add_port_option "[ ] DOCS"
add_port_option "[x] EXTRAS"
add_port_option "[x] GOLD"
add_port_option "[x] LIT"
add_port_option "[x] LLD"
add_port_option "[x] LLDB"
add_port_option "[x] OPENMP"
create_port_options


init_port_options "devel_m4" "m4" "1.4.17_1,1"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBSIGSEGV"
create_port_options


init_port_options "devel_mercurial" "mercurial" "3.9.1"
add_port_option "[ ] CA_BUNDLE"
add_port_option "[x] DATA"
add_port_option "[ ] DOCS"
add_port_option "[ ] FREEBSD"
add_port_option "[ ] NLS"
create_port_options


init_port_options "devel_nasm" "nasm" "2.11.05,1"
add_port_option "[ ] DOCS"
add_port_option "[x] RDOFF"
create_port_options


init_port_options "devel_nspr" "nspr" "4.10.10_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] TEST"
create_port_options


init_port_options "devel_pcre" "pcre" "8.39"
add_port_option "[ ] DOCS"
add_port_option "[x] MAN3"
add_port_option "[x] STACK_RECURSION"
add_port_option "( ) LIBEDIT"
add_port_option "( ) READLINE"
create_port_options


init_port_options "devel_pcre2" "pcre2" "10.21"
add_port_option "[ ] DOCS"
add_port_option "[x] STACK_RECURSION"
add_port_option "( ) LIBEDIT"
add_port_option "( ) READLINE"
create_port_options


init_port_options "devel_pydbus-common" "pydbus-common" "1.2.0_1"
add_port_option "[ ] HTMLDOCS"
create_port_options


init_port_options "devel_py-Jinja2" "py27-Jinja2" "2.7.3"
add_port_option "[x] BABEL"
add_port_option "[ ] EXAMPLES"
create_port_options


init_port_options "devel_readline" "readline" "6.3.6_1"
add_port_option "[ ] DOCS"
add_port_option "[x] TERMCAP"
create_port_options


init_port_options "devel_sdl12" "sdl" "1.2.15_7,2"
add_port_option "[ ] AALIB"
add_port_option "[ ] DOCS"
add_port_option "[ ] ESOUND"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] NAS"
add_port_option "[x] OPENGL"
add_port_option "[x] OSS"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SVGALIB"
add_port_option "[x] VGL"
add_port_option "[x] X11"
create_port_options


init_port_options "devel_sdl12" "sdl" "1.2.15_9,2"
add_port_option "[ ] AALIB"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] OPENGL"
add_port_option "[ ] SVGALIB"
add_port_option "[x] VGL"
add_port_option "[x] X11"
add_port_option "[ ] ESOUND"
add_port_option "[ ] NAS"
add_port_option "[x] OSS"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SNDIO"
create_port_options

init_port_options "devel_sdl20" "sdl2" "2.0.6"
add_port_option "[ ] ALSA"
add_port_option "[x] ASM"
add_port_option "[x] DLOPEN"
add_port_option "[ ] ESOUND"
add_port_option "[ ] JACK"
add_port_option "[ ] NAS"
add_port_option "[x] OSS"
add_port_option "[x] PTHREADS"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SAMPLERATE"
add_port_option "[x] SDL_ATOMIC"
add_port_option "[x] SDL_AUDIO"
add_port_option "[x] SDL_CPUINFO"
add_port_option "[x] SDL_EVENTS"
add_port_option "[x] SDL_FILE"
add_port_option "[x] SDL_HAPTIC"
add_port_option "[x] SDL_JOYSTICK"
add_port_option "[x] SDL_LOADSO"
add_port_option "[x] SDL_POWER"
add_port_option "[x] SDL_RENDER"
add_port_option "[x] SDL_THREADS"
add_port_option "[x] SDL_TIMERS"
add_port_option "[x] SDL_VIDEO"
add_port_option "[ ] SNDIO"
add_port_option "[x] VIDEO_KMSDRM"
add_port_option "[x] VIDEO_OPENGL"
add_port_option "[x] VIDEO_X11"
create_port_options


init_port_options "devel_subversion" "subversion" "1.9.5"
add_port_option "[ ] BDB"
add_port_option "[ ] DOCS"
add_port_option "[x] FREEBSD_TEMPLATE"
add_port_option "[ ] MAINTAINER_DEBUG"
add_port_option "[ ] NLS"
add_port_option "[ ] SASL"
add_port_option "[x] SERF"
add_port_option "[ ] STATIC"
add_port_option "[ ] SVNSERVE_WRAPPER"
add_port_option "[ ] TEST"
add_port_option "[ ] TOOLS"
create_port_options


init_port_options "devel_swig13" "swig13" "1.3.40_1"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LUA"
create_port_options


init_port_options "devel_talloc" "talloc" "2.1.0"
add_port_option "[ ] MANPAGES"
create_port_options


init_port_options "devel_tevent" "tevent" "0.9.21"
add_port_option "[ ] MANPAGES"
create_port_options


init_port_options "dns_dnsmasq" "dnsmasq" "2.76,1"
add_port_option "[ ] DBUS"
add_port_option "[ ] DNSSEC"
add_port_option "[ ] DOCS"
add_port_option "[ ] IPSET"
add_port_option "[x] IPV6"
add_port_option "[ ] LUA"
add_port_option "( ) IDN"
add_port_option "( ) NLS"
create_port_options


init_port_options "dns_py-dnspython" "py27-dnspython" "1.15.0"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] PYCRYPTO"
create_port_options


init_port_options "editors_libreoffice" "libreoffice" "5.2.5_5"
add_port_option "[x] CUPS"
add_port_option "[ ] GNOME"
add_port_option "[x] GTK2"
add_port_option "[ ] GTK3"
add_port_option "[ ] JAVA"
add_port_option "[ ] KDE4"
add_port_option "[ ] MMEDIA"
add_port_option "[ ] PGSQL"
add_port_option "[ ] SDK"
add_port_option "[ ] SYSTRAY"
add_port_option "[ ] TEST"
add_port_option "[ ] VERBOSE"
add_port_option "[ ] WEBDAV"
create_port_options


init_port_options "emulators_dosbox" "dosbox" "0.74_11"
add_port_option "( ) DEBUGGER_ENABLE"
add_port_option "( ) DEBUGGER_HEAVY"
create_port_options


init_port_options "emulators_qemu" "qemu" "2.9.0"
add_port_option "[x] CDROM_DMA"
add_port_option "[x] CURL"
add_port_option "[x] DOCS"
add_port_option "[x] GNS3"
add_port_option "[ ] GNUTLS"
add_port_option "[x] GTK2"
add_port_option "[x] JPEG"
add_port_option "[x] NCURSES"
add_port_option "[x] OPENGL"
add_port_option "[x] PCAP"
add_port_option "[x] PNG"
add_port_option "[ ] SAMBA"
add_port_option "[ ] SASL"
add_port_option "[ ] STATIC_LINK"
add_port_option "[ ] USBREDIR"
add_port_option "[x] VDE"
add_port_option "[x] X11"
add_port_option "[ ] X86_TARGETS"
create_port_options


init_port_options "emulators_virtualbox-ose-additions" "virtualbox-ose-additions" "5.0.26"
add_port_option "[x] DBUS"
add_port_option "[ ] DEBUG"
add_port_option "[x] OPENGL"
add_port_option "[x] X11"
create_port_options


init_port_options "ftp_curl" "curl" "7.51.0_1"
add_port_option "[x] CA_BUNDLE"
add_port_option "[x] COOKIES"
add_port_option "[ ] CURL_DEBUG"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] HTTP2"
add_port_option "[ ] IDN"
add_port_option "[x] IPV6"
add_port_option "[ ] LDAP"
add_port_option "[ ] LDAPS"
add_port_option "[ ] LIBSSH2"
add_port_option "[ ] METALINK"
add_port_option "[x] PROXY"
add_port_option "[ ] PSL"
add_port_option "[ ] RTMP"
add_port_option "[ ] SMB"
add_port_option "[x] TLS_SRP"
add_port_option "( ) GSSAPI_BASE"
add_port_option "( ) GSSAPI_HEIMDAL"
add_port_option "( ) GSSAPI_MIT"
add_port_option "(*) GSSAPI_NONE"
add_port_option "( ) CARES"
add_port_option "(*) THREADED_RESOLVER"
add_port_option "( ) GNUTLS"
add_port_option "( ) NSS"
add_port_option "(*) OPENSSL"
add_port_option "( ) POLARSSL"
add_port_option "( ) WOLFSSL"
create_port_options


init_port_options "ftp_wget" "wget" "1.19.1_1"
add_port_option "[ ] DOCS"
add_port_option "[ ] IDN"
add_port_option "[x] IPV6"
add_port_option "[x] MANPAGES"
add_port_option "[ ] METALINK"
add_port_option "[ ] NLS"
add_port_option "[ ] PCRE"
add_port_option "[ ] PSL"
add_port_option "( ) GNUTLS"
add_port_option "(*) OPENSSL"
create_port_options


init_port_options "graphics_blender" "blender" "2.78c_1"
add_port_option "[x] AVI"
add_port_option "[x] BULLET"
add_port_option "[ ] CAMERATRACK"
add_port_option "[ ] CINEON"
add_port_option "[ ] COLLADA"
add_port_option "[x] COMPOSITOR"
add_port_option "[ ] CYCLES"
add_port_option "[ ] CYCLESOSL"
add_port_option "[ ] DDS"
add_port_option "[ ] FFMPEG"
add_port_option "[x] FFTW3"
add_port_option "[ ] FRAMESERVER"
add_port_option "[x] FREESTYLE"
add_port_option "[x] GAMEENGINE"
add_port_option "[ ] HDR"
add_port_option "[ ] HEADLESS"
add_port_option "[ ] INPUT_NDOF"
add_port_option "[ ] JACK"
add_port_option "[x] LIBMV"
add_port_option "[x] LZMA"
add_port_option "[x] LZO"
add_port_option "[ ] MENU"
add_port_option "[x] MOD_BOOLEAN"
add_port_option "[x] MOD_FLUID"
add_port_option "[ ] MOD_OCEANSIM"
add_port_option "[x] MOD_REMESH"
add_port_option "[x] MOD_SMOKE"
add_port_option "[ ] NLS"
add_port_option "[x] OPENAL"
add_port_option "[x] OPENCOLORIO"
add_port_option "[x] OPENEXR"
add_port_option "[x] OPENIMAGEIO"
add_port_option "[x] OPENJPEG"
add_port_option "[x] OPENSUBDIV"
add_port_option "[x] PLAYER"
add_port_option "[ ] RAYOPTIMIZATION"
add_port_option "[ ] REDCODE"
add_port_option "[x] SDL"
add_port_option "[ ] SNDFILE"
add_port_option "[x] TIFF"
add_port_option "[x] XF86VMODE"
add_port_option "[x] XINPUT"
create_port_options


init_port_options "graphics_cairo" "cairo" "1.10.2_5,2"
add_port_option "[x] GLIB"
add_port_option "[ ] OPENGL"
add_port_option "[x] X11"
add_port_option "[x] XCB"
create_port_options


init_port_options "graphics_colord" "colord" "1.2.11"
add_port_option "[ ] MANPAGES"
add_port_option "[ ] PPROFILES"
create_port_options


init_port_options "graphics_dri" "dri" "17.0.3,2"
add_port_option "[x] TEXTURE"
add_port_option "[ ] VAAPI"
add_port_option "[ ] VDPAU"
create_port_options


init_port_options "graphics_epdfview" "epdfview" "0.1.8_4"
add_port_option "[ ] CUPS"
add_port_option "[ ] NLS"
create_port_options


init_port_options "graphics_gdk-pixbuf2" "gdk-pixbuf2" "2.31.5"
add_port_option "[x] JASPER"
add_port_option "[x] JPEG"
add_port_option "[ ] NLS"
add_port_option "[x] PNG"
add_port_option "[x] TIFF"
create_port_options


init_port_options "graphics_gegl" "gegl" "0.2.0_19"
add_port_option "[x] CAIRO"
add_port_option "[ ] DOCS"
add_port_option "[x] ENSCRIPT"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] EXIV2"
add_port_option "[ ] FFMPEG"
add_port_option "[ ] GRAPHVIZ"
add_port_option "[ ] JASPER"
add_port_option "[x] JPEG"
add_port_option "[x] LIBRSVG2"
add_port_option "[ ] LUA"
add_port_option "[ ] OPENEXR"
add_port_option "[x] OPENRAW"
add_port_option "[x] PANGO"
add_port_option "[x] PIXBUF"
add_port_option "[x] PNG"
add_port_option "[x] SDL"
add_port_option "[ ] SIMD"
add_port_option "[x] SPIRO"
add_port_option "[x] V4L"
create_port_options


init_port_options "graphics_giflib" "giflib-nox11" "4.2.3"
add_port_option "[ ] DOCBOOK"
add_port_option "[ ] DOCS"
add_port_option "[ ] X11"
create_port_options


init_port_options "graphics_gimp" "gimp" "2.8.18,2"
add_port_option "[ ] HELP"
add_port_option "[ ] PRINT"
add_port_option "[ ] PYTHON"
create_port_options


init_port_options "graphics_gimp-app" "gimp-app" "2.8.18_2,2"
add_port_option "[ ] AA"
add_port_option "[x] DBUS"
add_port_option "[ ] GHOSTSCRIPT"
add_port_option "[ ] GVFS"
add_port_option "[ ] HELPBROWSER"
add_port_option "[ ] JASPER"
add_port_option "[x] LIBEXIF"
add_port_option "[ ] LIBMNG"
add_port_option "[x] LIBRSVG2"
add_port_option "[ ] POPPLER"
add_port_option "[ ] SIMD"
add_port_option "[ ] WMF"
create_port_options


init_port_options "graphics_ImageMagick" "ImageMagick" "6.9.1.1,1"
add_port_option "[x] BZIP2"
add_port_option "[ ] DJVU"
add_port_option "[ ] DOCS"
add_port_option "[ ] FFTW"
add_port_option "[x] FONTCONFIG"
add_port_option "[ ] FPX"
add_port_option "[ ] FREETYPE"
add_port_option "[ ] GRAPHVIZ"
add_port_option "[ ] GSLIB"
add_port_option "[x] JBIG"
add_port_option "[x] JPEG"
add_port_option "[x] JPEG2000"
add_port_option "[x] LCMS2"
add_port_option "[x] LQR"
add_port_option "[x] LZMA"
add_port_option "[ ] MODULES"
add_port_option "[ ] OPENEXR"
add_port_option "[ ] OPENMP"
add_port_option "[ ] PANGO"
add_port_option "[ ] PDF"
add_port_option "[x] PERL"
add_port_option "[x] PNG"
add_port_option "[ ] SVG"
add_port_option "[ ] TESTS"
add_port_option "[ ] THREADS"
add_port_option "[x] TIFF"
add_port_option "[x] WEBP"
add_port_option "[ ] WMF"
add_port_option "[ ] X11"
add_port_option "[x] 16BIT_PIXEL"
add_port_option "[ ] HDRI"
create_port_options


init_port_options "graphics_imlib2" "imlib2" "1.4.5_2,2"
add_port_option "[ ] GIF"
add_port_option "[ ] ID3"
add_port_option "[x] JPEG"
add_port_option "[x] PNG"
add_port_option "[x] TIFF"
add_port_option "[x] X11"
create_port_options


init_port_options "graphics_inkscape" "inkscape" "0.92.0"
add_port_option "[ ] CDR"
add_port_option "[ ] DBUS"
add_port_option "[x] POPPLER"
add_port_option "[ ] VISIO"
add_port_option "[ ] WPG"
create_port_options


init_port_options "graphics_jasper" "jasper" "1.900.1_14"
add_port_option "[ ] DOCS"
add_port_option "[ ] OPENGL"
add_port_option "[ ] UUID"
create_port_options


init_port_options "graphics_lcms" "lcms" "1.19_6,1"
add_port_option "[ ] DOCS"
add_port_option "[x] JPEGICC"
add_port_option "[x] TIFFICC"
create_port_options


init_port_options "graphics_lcms2" "lcms2" "2.4"
add_port_option "[ ] DOCS"
add_port_option "[ ] JPEGICC"
add_port_option "[ ] TIFFICC"
create_port_options


init_port_options "graphics_libdrm" "libdrm" "2.4.81,1"
add_port_option "[ ] MANPAGES"
add_port_option "[ ] TESTS"
create_port_options


init_port_options "graphics_libepoxy" "libepoxy" "1.4.3"
add_port_option "[x] EGL"
create_port_options


init_port_options "graphics_libetonyek01" "libetonyek01" "0.1.6_3,1"
add_port_option "[ ] TEST"
create_port_options


init_port_options "graphics_liblqr-1" "liblqr-1" "0.4.1_8"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] HTMLDOCS"
create_port_options


init_port_options "graphics_libmng" "libmng" "1.0.10_3"
add_port_option "[ ] MNG_OPTIMIZE"
create_port_options


init_port_options "graphics_libopenraw" "libopenraw" "0.1.1"
add_port_option "[ ] GNOME"
add_port_option "[ ] TEST"
create_port_options


init_port_options "graphics_libpotrace" "libpotrace" "1.12"
add_port_option "[x] A4"
add_port_option "[x] METRIC"
create_port_options


init_port_options "graphics_mesa-dri" "mesa-dri" "17.0.4"
add_port_option "[x] TEXTURE"
add_port_option "[ ] VAAPI"
add_port_option "[ ] VDPAU"
create_port_options


init_port_options "graphics_mesa-libs" "mesa-libs" "17.0.4"
add_port_option "[ ] WAYLAND"
create_port_options


init_port_options "graphics_OpenEXR" "OpenEXR" "2.2.0_7"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LARGE_STACK"
create_port_options


init_port_options "graphics_openimageio" "openimageio" "1.6.12_8"
add_port_option "[ ] DOCS"
add_port_option "[ ] FFMPEG"
add_port_option "[x] FREETYPE"
add_port_option "[ ] GIF"
add_port_option "[ ] IMAGEVIEWER"
add_port_option "[x] OCIO"
add_port_option "[ ] OPENCV"
add_port_option "[x] OPENJPEG"
add_port_option "[ ] RAW"
add_port_option "[ ] TEST"
create_port_options


init_port_options "graphics_png" "png" "1.5.18"
add_port_option "[x] APNG"
add_port_option "[ ] PNGTEST"
create_port_options


init_port_options "graphics_poppler" "poppler" "0.26.3"
add_port_option "[x] CAIRO"
add_port_option "[ ] CURL"
add_port_option "[x] OPENJPEG"
create_port_options


init_port_options "graphics_rawtherapee" "rawtherapee" "5.0.1"
add_port_option "[ ] NATIVE"
add_port_option "[x] OPENMP"
add_port_option "[x] OPTIMIZED_CFLAGS"
create_port_options


init_port_options "graphics_sane-backends" "sane-backends" "1.0.25"
add_port_option "[ ] AVAHI"
add_port_option "[ ] DOCS"
add_port_option "[ ] GPHOTO"
add_port_option "[ ] IEEE1284"
add_port_option "[x] IPV6"
add_port_option "[ ] NLS"
add_port_option "[ ] SNMP"
add_port_option "[x] USB"
add_port_option "[ ] V4L"
create_port_options


init_port_options "graphics_vigra" "vigra" "1.11.0_10"
add_port_option "[ ] DOCS"
add_port_option "[x] FFTW"
add_port_option "[ ] HDF5"
add_port_option "[ ] NUMPY"
add_port_option "[ ] OPENEXR"
add_port_option "[x] PNG"
add_port_option "[x] JPEG"
add_port_option "[x] TIFF"
create_port_options


init_port_options "graphics_webp" "webp" "0.3.1_4"
add_port_option "[ ] X11"
create_port_options


init_port_options "lang_gcc6" "gcc6" "6.4.0_1"
add_port_option "[x] BOOTSTRAP"
add_port_option "[ ] GRAPHITE"
add_port_option "[ ] JAVA"
create_port_options


init_port_options "lang_guile2" "guile2" "2.0.14"
add_port_option "[ ] NLS"
add_port_option "[x] THREADS"
create_port_options


init_port_options "lang_perl5.24" "perl5" "5.24.1.r4_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DTRACE"
add_port_option "[ ] GDBM"
add_port_option "[x] MULTIPLICITY"
add_port_option "[x] PERL_64BITINT"
add_port_option "[x] PTHREAD"
add_port_option "[ ] SITECUSTOMIZE"
add_port_option "(*) THREADS"
add_port_option "( ) PERL_MALLOC"
create_port_options


init_port_options "lang_python27" "python27" "2.7.8_6"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[x] SEM"
add_port_option "[x] THREADS"
add_port_option "( ) UCS2"
add_port_option "(*) UCS4"
create_port_options


init_port_options "lang_python36" "python36" "3.6.1_1"
add_port_option "[ ] DEBUG"
add_port_option "[x] IPV6"
add_port_option "[x] LIBFFI"
add_port_option "[ ] NLS"
add_port_option "[x] PYMALLOC"
add_port_option "[x] THREADS"
add_port_option "( ) FNV"
add_port_option "( ) SIPHASH"
create_port_options


init_port_options "lang_ruby23" "ruby" "2.3.3_2,1"
add_port_option "[ ] CAPIDOCS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] GMP"
add_port_option "[ ] RDOC"
add_port_option "(*) LIBEDIT"
add_port_option "( ) READLINE"
create_port_options


init_port_options "lang_rust" "rust" "1.19.0_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] GDB"
add_port_option "[ ] LLNEXTGEN"
add_port_option "[ ] PORT_LLVM"
add_port_option "[ ] SOURCES"
create_port_options


init_port_options "lang_spidermonkey170" "spidermonkey170" "17.0.0_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DTRACE"
add_port_option "[ ] GCZEAL"
add_port_option "[ ] JEMALLOC"
add_port_option "[x] METHODJIT"
add_port_option "[x] OPTIMIZE"
add_port_option "[x] READLINE"
add_port_option "[x] THREADSAFE"
add_port_option "[x] TRACEJIT"
add_port_option "[x] UTF8"
create_port_options


init_port_options "mail_thunderbird" "thunderbird" "45.7.1_1"
add_port_option "[x] BUNDLED_CAIRO"
add_port_option "[x] CANBERRA"
add_port_option "[x] DBUS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DTRACE"
add_port_option "[ ] FFMPEG"
add_port_option "[ ] GCONF"
add_port_option "[ ] GNOMEUI"
add_port_option "[ ] INTEGER_SAMPLES"
add_port_option "[ ] LIBPROXY"
add_port_option "[x] LIGHTNING"
add_port_option "[x] OPTIMIZED_CFLAGS"
add_port_option "[ ] PGO"
add_port_option "[ ] PROFILE"
add_port_option "[ ] RUST"
add_port_option "[ ] TEST"
add_port_option "[x] ALSA"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SNDIO"
add_port_option "(*) GTK2"
add_port_option "( ) GTK3"
create_port_options


init_port_options "math_coinmp" "CoinMP" "1.83"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] GLPK"
create_port_options


init_port_options "math_fftw3" "fftw3" "3.3.6.p1"
add_port_option "[ ] G77_WRAPPERS"
add_port_option "[ ] OPENMP"
add_port_option "[ ] OPENMPI"
add_port_option "[x] OPTIMIZED_CFLAGS"
add_port_option "[x] SIMD"
create_port_options


init_port_options "math_fftw3-float" "fftw3-float" "3.3.6.p1"
add_port_option "[ ] G77_WRAPPERS"
add_port_option "[ ] OPENMP"
add_port_option "[ ] OPENMPI"
add_port_option "[x] OPTIMIZED_CFLAGS"
add_port_option "[x] SIMD"
create_port_options


init_port_options "math_galculator" "galculator" "2.1.4"
add_port_option "( ) GTK2"
add_port_option "(*) GTK3"
create_port_options


init_port_options "math_gmp" "gmp" "5.1.3_1"
add_port_option "[ ] CPU_OPTS"
create_port_options


init_port_options "multimedia_avidemux" "avidemux" "2.6.11_5"
add_port_option "[ ] AMR"
add_port_option "[ ] CLI"
add_port_option "[ ] ESOUND"
add_port_option "[x] FAAC"
add_port_option "[x] FAAD"
add_port_option "[ ] FONTCONFIG"
add_port_option "[ ] FREETYPE"
add_port_option "[ ] FRIBIDI"
add_port_option "[ ] JACK"
add_port_option "[ ] LAME"
add_port_option "[ ] NLS"
add_port_option "[ ] OPUS"
add_port_option "[ ] OSS"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[x] QT4"
add_port_option "[x] SDL"
add_port_option "[ ] TWOLAME"
add_port_option "[ ] VAAPI"
add_port_option "[x] VDPAU"
add_port_option "[x] VORBIS"
add_port_option "[x] VPX"
add_port_option "[x] X264"
add_port_option "[ ] X265"
add_port_option "[x] XVID"
add_port_option "[x] XVIDEO"
create_port_options


init_port_options "multimedia_ffmpeg" "ffmpeg" "3.3.4,1"
add_port_option "[ ] ALSA"
add_port_option "[ ] AMR_NB"
add_port_option "[ ] AMR_WB"
add_port_option "[ ] ASS"
add_port_option "[ ] BS2B"
add_port_option "[ ] CACA"
add_port_option "[ ] CDIO"
add_port_option "[ ] CELT"
add_port_option "[ ] CHROMAPRINT"
add_port_option "[ ] DC1394"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[X] FDK_AAC"
add_port_option "[ ] FFSERVER"
add_port_option "[ ] FLITE"
add_port_option "[x] FONTCONFIG"
add_port_option "[x] FREETYPE"
add_port_option "[ ] FREI0R"
add_port_option "[ ] FRIBIDI"
add_port_option "[ ] GME"
add_port_option "[ ] GSM"
add_port_option "[x] ICONV"
add_port_option "[ ] ILBC"
add_port_option "[ ] JACK"
add_port_option "[ ] KVAZAAR"
add_port_option "[ ] LADSPA"
add_port_option "[ ] LAME"
add_port_option "[x] LIBBLURAY"
add_port_option "[ ] MODPLUG"
add_port_option "[x] NEON"
add_port_option "[ ] NETCDF"
add_port_option "[ ] OPENAL"
add_port_option "[ ] OPENCL"
add_port_option "[ ] OPENCV"
add_port_option "[ ] OPENGL"
add_port_option "[ ] OPENH264"
add_port_option "[ ] OPENJPEG"
add_port_option "[x] OPTIMIZED_CFLAGS"
add_port_option "[x] OPUS"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[x] RTCPU"
add_port_option "[ ] RUBBERBAND"
add_port_option "[ ] SCHROEDINGER"
add_port_option "[ ] SDL"
add_port_option "[ ] SMB"
add_port_option "[ ] SNAPPY"
add_port_option "[ ] SNDIO"
add_port_option "[ ] SOXR"
add_port_option "[ ] SPEEX"
add_port_option "[ ] SSH"
add_port_option "[ ] TESSERACT"
add_port_option "[ ] THEORA"
add_port_option "[ ] TWOLAME"
add_port_option "[ ] V4L"
add_port_option "[ ] VAAPI"
add_port_option "[ ] VDPAU"
add_port_option "[x] VFP"
add_port_option "[ ] VIDSTAB"
add_port_option "[ ] VORBIS"
add_port_option "[ ] VO_AMRWBENC"
add_port_option "[x] VPX"
add_port_option "[ ] WAVPACK"
add_port_option "[ ] WEBP"
add_port_option "[x] X264"
add_port_option "[x] X265"
add_port_option "[ ] XCB"
add_port_option "[ ] XVID"
add_port_option "[ ] XVIDEO"
add_port_option "[ ] ZIMG"
add_port_option "[ ] ZMQ"
add_port_option "[ ] ZVBI"
add_port_option "[x] GPL3"
add_port_option "[x] NONFREE"
add_port_option "( ) GCRYPT"
add_port_option "(*) GMP"
add_port_option "( ) LIBRTMP"
add_port_option "(*) GNUTLS"
add_port_option "( ) OPENSSL"
create_port_options


init_port_options "multimedia_gmtk" "gmtk" "1.0.8"
add_port_option "[ ] ALSA"
add_port_option "[ ] DOCS"
add_port_option "[ ] GCONF"
add_port_option "[ ] GIO"
add_port_option "[ ] GTK3"
add_port_option "[x] NLS"
add_port_option "[ ] PULSEAUDIO"
create_port_options


init_port_options "multimedia_gstreamer" "gstreamer" "0.10.36_6"
add_port_option "[ ] LIBCHECK"
add_port_option "[ ] NLS"
create_port_options


init_port_options "multimedia_gstreamer1" "gstreamer1" "1.8.0_1"
add_port_option "[ ] LIBCHECK"
create_port_options


init_port_options "multimedia_gstreamer1-plugins-core" "gstreamer1-plugins-core" "1.12"
add_port_option "[x] DVD"
create_port_options


init_port_options "multimedia_libass" "libass" "0.13.6_1"
add_port_option "[x] ASM"
add_port_option "[x] HARFBUZZ"
create_port_options


init_port_options "multimedia_libbluray" "libbluray" "0.2.2,1"
add_port_option "[ ] JAVA"
create_port_options


init_port_options "multimedia_libdvdnav" "libdvdnav" "4.2.1_2"
add_port_option "[ ] DEBUG"
create_port_options


init_port_options "multimedia_libdvdread" "libdvdread" "4.9.9_3"
add_port_option "[ ] DVDCSS"
create_port_options


init_port_options "multimedia_libmediainfo" "libmediainfo" "0.7.94"
add_port_option "[ ] CURL"
add_port_option "[ ] MMS"
add_port_option "[x] TINYXML2"
create_port_options


init_port_options "multimedia_libva" "libva" "1.7.3"
add_port_option "[ ] DEBUG"
create_port_options


init_port_options "multimedia_libvdpau" "libvdpau" "1.1.1"
add_port_option "[ ] DEBUG"
create_port_options


init_port_options "multimedia_libvpx" "libvpx" "1.6.1_2"
add_port_option "[ ] DEBUG"
add_port_option "[x] MULTIRES"
add_port_option "[x] POSTPROC"
add_port_option "[x] RTCPU"
add_port_option "[x] SHARED"
add_port_option "[x] SIZE_LIMIT"
add_port_option "[ ] TEST"
add_port_option "[x] THREADS"
create_port_options


init_port_options "multimedia_libx264" "libx264" "0.148.2728"
add_port_option "[x] ASM"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GCC"
add_port_option "[ ] HI10P"
add_port_option "[ ] OPENCL"
add_port_option "[ ] PGO"
create_port_options


init_port_options "multimedia_mplayer" "mplayer" "1.3.0.20161228_4"
add_port_option "[ ] AALIB"
add_port_option "[ ] AMR_NB"
add_port_option "[ ] AMR_WB"
add_port_option "[x] ASS"
add_port_option "[x] BLURAY"
add_port_option "[ ] CACA"
add_port_option "[ ] CDIO"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DV"
add_port_option "[x] DVDNAV"
add_port_option "[ ] ENCA"
add_port_option "[x] FONTCONFIG"
add_port_option "[ ] FRIBIDI"
add_port_option "[ ] GIF"
add_port_option "[ ] GNUTLS"
add_port_option "[ ] GSM"
add_port_option "[ ] GUI"
add_port_option "[x] IPV6"
add_port_option "[ ] JACK"
add_port_option "[ ] LADSPA"
add_port_option "[ ] LIBMNG"
add_port_option "[ ] LIRC"
add_port_option "[ ] LZO"
add_port_option "[ ] NAS"
add_port_option "[ ] OPENAL"
add_port_option "[x] OPENGL"
add_port_option "[ ] OPENJPEG"
add_port_option "[ ] OPUS"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] RTC"
add_port_option "[x] RTCPU"
add_port_option "[ ] RTMP"
add_port_option "[ ] SCHROEDINGER"
add_port_option "[ ] SDL"
add_port_option "[ ] SKINS"
add_port_option "[ ] SMB"
add_port_option "[ ] SNDIO"
add_port_option "[ ] SPEEX"
add_port_option "[ ] SVGALIB"
add_port_option "[ ] V4L"
add_port_option "[ ] VDPAU"
add_port_option "[ ] VPX"
add_port_option "[x] X11"
add_port_option "[x] X11DGA"
add_port_option "[x] X11VM"
add_port_option "[x] XINERAMA"
add_port_option "[x] XVIDEO"
add_port_option "[x] XVMC"
create_port_options


init_port_options "multimedia_qmmp-qt5" "qmmp-qt5" "1.1.7"
add_port_option "[ ] DOCS"
add_port_option "[ ] DOXYGEN"
add_port_option "[ ] GNOMEHOTKEY"
add_port_option "[x] HOTKEY"
add_port_option "[ ] KDENOTIFY"
add_port_option "[x] NOTIFIER"
add_port_option "[x] QMMP_DIALOG"
add_port_option "[x] QSUI"
add_port_option "[x] SKINNEDUI"
add_port_option "[x] STATICON"
add_port_option "[x] TWOPANELDIALOG"
add_port_option "[ ] CDDA"
add_port_option "[x] FAAD"
add_port_option "[x] FFMPEG"
add_port_option "[x] FLAC"
add_port_option "[ ] GME"
add_port_option "[x] MAD"
add_port_option "[ ] MODPLUG"
add_port_option "[ ] MUSEPACK"
add_port_option "[x] OPUS"
add_port_option "[x] SNDFILE"
add_port_option "[x] VORBIS"
add_port_option "[x] WAVPACK"
add_port_option "[x] WILDMIDI"
add_port_option "[x] BS2B"
add_port_option "[x] CROSSFADE"
add_port_option "[x] LADSPA"
add_port_option "[x] SOXR"
add_port_option "[x] STEREO"
add_port_option "[x] ANALYZER"
add_port_option "[x] PROJECTM"
add_port_option "[x] ALSA"
add_port_option "[ ] JACK"
add_port_option "[x] NULLOUT"
add_port_option "[ ] OSS"
add_port_option "[ ] OSS4"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[x] QTMULTIMEDIA"
add_port_option "[x] COPYPASTE"
add_port_option "[x] DIR_ASSOC"
add_port_option "[x] FILEOPS"
add_port_option "[ ] HAL"
add_port_option "[ ] TRACKCHANGE"
add_port_option "[ ] UDISKS2"
add_port_option "[ ] COVER"
add_port_option "[ ] CURL"
add_port_option "[ ] LYRICS"
add_port_option "[ ] MMS"
add_port_option "[ ] SB"
add_port_option "[ ] SCROBBLER"
add_port_option "[ ] CONVERTER"
add_port_option "[x] CUE"
add_port_option "[x] ENCA"
add_port_option "[ ] MPLAYER"
add_port_option "[ ] MPRIS"
add_port_option "[x] RGSCAN"
add_port_option "[x] SID"
create_port_options


init_port_options "multimedia_qt5-multimedia" "qt5-multimedia" "5.7.1"
add_port_option "[ ] AUDIOPLUGIN"
add_port_option "[x] GSTREAMER"
add_port_option "[ ] OPENAL"
add_port_option "( ) ALSA"
add_port_option "( ) PULSEAUDIO"
create_port_options


init_port_options "multimedia_smplayer" "smplayer" "17.1.0"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
create_port_options


init_port_options "multimedia_xvid" "xvid" "1.3.4,1"
add_port_option "[ ] OPTIMIZED_CFLAGS"
create_port_options


init_port_options "net_gtk-vnc" "gtk-vnc" "0.7.0"
add_port_option "[ ] PULSEAUDIO"
create_port_options


init_port_options "net_miniupnpd" "miniupnpd" "1.9.20160113,1"
add_port_option "[ ] CHECK_PORTINUSE"
add_port_option "[x] IPV6"
add_port_option "[ ] LEASEFILE"
add_port_option "[x] PF_FILTER_RULES"
add_port_option "[ ] UPNP_IGDV2"
add_port_option "[ ] UPNP_STRICT"
create_port_options


init_port_options "net_mpd5" "mpd" "5.7"
add_port_option "[ ] NG_IPACCT"
create_port_options


init_port_options "net_openldap24-client" "openldap-client" "2.4.40_1"
add_port_option "[ ] DEBUG"
add_port_option "[ ] FETCH"
add_port_option "[ ] GSSAPI"
create_port_options


init_port_options "net_samba46" "samba46" "4.6.1_1"
add_port_option "[ ] ADS"
add_port_option "[ ] AD_DC"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DEVELOPER"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXP_MODULES"
add_port_option "[ ] FAM"
add_port_option "[ ] LDAP"
add_port_option "[ ] MANPAGES"
add_port_option "[ ] NTVFS"
add_port_option "[ ] QUOTAS"
add_port_option "[ ] SYSLOG"
add_port_option "[ ] UTMP"
add_port_option "( ) NSUPDATE"
add_port_option "( ) BIND99"
add_port_option "( ) BIND910"
add_port_option "( ) BIND911"
add_port_option "( ) AVAHI"
add_port_option "( ) MDNSRESPONDER"
create_port_options


init_port_options "net_wireshark-qt5" "wireshark-qt5" "2.2.5"
add_port_option "[ ] ANDROIDDUMP"
add_port_option "[ ] CARES"
add_port_option "[ ] DECRYPT"
add_port_option "[ ] GEOIP"
add_port_option "[x] IPV6"
add_port_option "[ ] LUA"
add_port_option "[ ] RTP"
add_port_option "[ ] SNMP"
add_port_option "( ) KRB_BASE"
add_port_option "( ) KRB_HEIMDAL"
add_port_option "( ) KRB_MIT"
add_port_option "(*) KRB_NONE"
add_port_option "(*) QT5"
create_port_options


init_port_options "net_vde2" "vde2" "2.3.2_2"
add_port_option "[x] PYTHON"
create_port_options


init_port_options "net-p2p_transmission-cli" "transmission-cli" "2.92"
add_port_option "[ ] DOCS"
add_port_option "[ ] LITE"
add_port_option "(*) OPENSSL"
add_port_option "( ) POLARSSL"
add_port_option "( ) WOLFSSL"
create_port_options


init_port_options "net-p2p_transmission-daemon" "transmission-daemon" "2.92"
add_port_option "[ ] DOCS"
add_port_option "[ ] LITE"
add_port_option "(*) OPENSSL"
add_port_option "( ) POLARSSL"
add_port_option "( ) WOLFSSL"
create_port_options


init_port_options "ports-mgmt_portmaster" "portmaster" "3.17"
add_port_option "[ ] BASH"
add_port_option "[ ] ZSH"
create_port_options


init_port_options "print_cups" "cups" "2.2.2_1"
add_port_option "[ ] AVAHI"
add_port_option "[x] DBUS"
add_port_option "[ ] DOCS"
add_port_option "[ ] GNUTLS"
add_port_option "[ ] IPPTOOL"
add_port_option "[x] LIBPAPER"
add_port_option "[ ] NLS"
add_port_option "[ ] X11"
create_port_options


init_port_options "print_fontforge" "fontforge" "20161005"
add_port_option "[ ] CAIRO"
add_port_option "[ ] DOCS"
add_port_option "[ ] FREETYPE"
add_port_option "[ ] PYTHON"
create_port_options


init_port_options "print_freetype2" "freetype2" "2.8"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] LCD_FILTERING"
add_port_option "[ ] PNG"
add_port_option "[ ] TABLE_VALIDATION"
add_port_option "[ ] TT_SIZE_METRICS"
add_port_option "[ ] V38"
add_port_option "[x] V40"
create_port_options


init_port_options "print_qt5-printsupport" "qt5-printsupport" "5.7.1"
add_port_option "[x] CUPS"
create_port_options


init_port_options "science_hdf5" "hdf5" "1.10.0_3"
add_port_option "[ ] DEBUG"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] FORTRAN"
add_port_option "[x] SZIP"
create_port_options


init_port_options "security_ca_root_nss" "ca_root_nss" "3.15.5"
add_port_option "[ ] ETCSYMLINK"
create_port_options


init_port_options "security_cyrus-sasl2" "cyrus-sasl" "2.1.26_12"
add_port_option "[ ] ALWAYSTRUE"
add_port_option "[x] AUTHDAEMOND"
add_port_option "[ ] DOCS"
add_port_option "[ ] KEEP_DB_OPEN"
add_port_option "[x] OBSOLETE_CRAM_ATTR"
add_port_option "[ ] MYSQL"
add_port_option "[ ] PGSQL"
add_port_option "[x] ANONYMOUS"
add_port_option "[x] CRAM"
add_port_option "[x] DIGEST"
add_port_option "[x] LOGIN"
add_port_option "[x] NTLM"
add_port_option "[x] OTP"
add_port_option "[x] PLAIN"
add_port_option "[x] SCRAM"
add_port_option "(*) BDB1"
add_port_option "( ) BDB"
add_port_option "( ) GDBM"
add_port_option "( ) SQLITE2"
add_port_option "( ) SQLITE3"
create_port_options


init_port_options "security_gnutls" "gnutls" "3.5.13"
add_port_option "[ ] DANE"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] IDN"
add_port_option "[ ] NLS"
add_port_option "[ ] P11KIT"
add_port_option "[ ] TPM"
add_port_option "[x] ZLIB"
create_port_options


init_port_options "security_libssh2" "libssh2" "1.8.0,3"
add_port_option "[ ] GCRYPT"
add_port_option "[ ] TRACE"
add_port_option "[x] ZLIB"
create_port_options


init_port_options "security_nss" "nss" "3.17.3"
add_port_option "[ ] DEBUG"
create_port_options


init_port_options "security_openvpn" "openvpn" "2.4.0"
add_port_option "[ ] DOCS"
add_port_option "[ ] EASYRSA"
add_port_option "[ ] EXAMPLES"
add_port_option "[x] LZ4"
add_port_option "[ ] PKCS11"
add_port_option "[ ] SMALL"
add_port_option "[ ] TEST"
add_port_option "[ ] TUNNELBLICK"
add_port_option "[ ] X509ALTUSERNAME"
add_port_option "(*) OPENSSL"
add_port_option "( ) MBEDTLS"
create_port_options


init_port_options "shells_bash" "bash" "4.4.12_2"
add_port_option "[x] COLONBREAKSWORDS"
add_port_option "[ ] DOCS"
add_port_option "[ ] FDESCFS"
add_port_option "[ ] HELP"
add_port_option "[ ] NLS"
add_port_option "[ ] STATIC"
add_port_option "[ ] SYSLOG"
create_port_options


init_port_options "shells_zsh" "zsh" "5.2_2"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DOCS"
add_port_option "[ ] ETCDIR"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] GDBM"
add_port_option "[ ] MEM"
add_port_option "[ ] PCRE"
add_port_option "[ ] STATIC"
create_port_options


init_port_options "sysutils_cdrtools" "cdrtools" "3.00_2"
add_port_option "[ ] CDDA2MP3"
add_port_option "[ ] CDDA2OGG"
add_port_option "[ ] DOCS"
add_port_option "[ ] NLS"
add_port_option "[ ] RSCSI"
create_port_options


init_port_options "sysutils_polkit" "polkit" "0.105_1"
add_port_option "[ ] MANPAGES"
create_port_options


init_port_options "sysutils_tmux" "tmux" "2.3_2"
add_port_option "[ ] BACKSPACE"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LIBEVENT_STATIC"
create_port_options


init_port_options "textproc_aspell" "aspell" "0.60.6.1_2"
add_port_option "[ ] DOCS"
add_port_option "[ ] ISPELL"
add_port_option "[x] NLS"
create_port_options


init_port_options "textproc_docbook-xsl" "docbook-xsl" "1.76.1_3"
add_port_option "[ ] DOCS"
add_port_option "[ ] ECLIPSE"
add_port_option "[x] EPUB"
add_port_option "[x] EXTENSIONS"
add_port_option "[x] HIGHLIGHTING"
add_port_option "[x] HTMLHELP"
add_port_option "[ ] JAVAHELP"
add_port_option "[x] PROFILING"
add_port_option "[x] ROUNDTRIP"
add_port_option "[ ] SLIDES"
add_port_option "[x] TEMPLATE"
add_port_option "[x] TESTS"
add_port_option "[x] TOOLS"
add_port_option "[x] WEBSITE"
add_port_option "[x] XHTML11"
create_port_options


init_port_options "textproc_enchant" "enchant" "1.6.0_7"
add_port_option "[ ] ASPELL"
add_port_option "[ ] HSPELL"
add_port_option "[x] HUNSPELL"
add_port_option "[ ] ISPELL"
add_port_option "[ ] ZEMBEREK"
create_port_options


init_port_options "textproc_librevenge" "librevenge" "0.0.4_3"
add_port_option "[ ] DOXYGEN"
create_port_options


init_port_options "textproc_libxml2" "libxml2" "2.9.2_3"
add_port_option "[ ] MEM_DEBUG"
add_port_option "[x] SCHEMA"
add_port_option "[x] THREADS"
add_port_option "[ ] THREAD_ALLOC"
add_port_option "[x] VALID"
add_port_option "[ ] XMLLINT_HIST"
create_port_options


init_port_options "textproc_libxslt" "libxslt" "1.1.28_1"
add_port_option "[x] CRYPTO"
add_port_option "[ ] MEM_DEBUG"
create_port_options


init_port_options "textproc_py-docutils" "py27-docutils" "0.12"
add_port_option "[ ] PYGMENTS"
create_port_options


init_port_options "textproc_py-snowballstemmer" "py27-snowballstemmer" "1.2.0_1"
add_port_option "[x] PYSTEMMER"
create_port_options


init_port_options "textproc_rasqal" "rasqal" "0.9.33"
add_port_option "[ ] GMP"
add_port_option "[ ] MPFR"
create_port_options


init_port_options "textproc_redland" "redland" "1.0.17_4"
add_port_option "[ ] BDB"
add_port_option "[ ] THREADS"
create_port_options


init_port_options "textproc_tinyxml" "tinyxml" "2.6.2_1"
add_port_option "[ ] DOCS"
add_port_option "[ ] PROFILE"
create_port_options


init_port_options "www_firefox" "firefox" "52.0_3,1"
add_port_option "[x] BUNDLED_CAIRO"
add_port_option "[ ] CANBERRA"
add_port_option "[x] DBUS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DTRACE"
add_port_option "[x] FFMPEG"
add_port_option "[ ] GCONF"
add_port_option "[ ] GNOMEUI"
add_port_option "[ ] INTEGER_SAMPLES"
add_port_option "[ ] LIBPROXY"
add_port_option "[ ] OPTIMIZED_CFLAGS"
add_port_option "[ ] PGO"
add_port_option "[ ] PROFILE"
add_port_option "[x] RUST"
add_port_option "[ ] TEST"
add_port_option "[x] ALSA"
add_port_option "[ ] PULSEAUDIO"
add_port_option "[ ] SNDIO"
add_port_option "( ) GTK2"
add_port_option "(*) GTK3"
create_port_options


init_port_options "www_nginx" "nginx" "1.12.1_1,2"
add_port_option "[x] DSO"
add_port_option "[ ] DEBUG"
add_port_option "[ ] DEBUGLOG"
add_port_option "[ ] FILE_AIO"
add_port_option "[x] IPV6"
add_port_option "[ ] GOOGLE_PERFTOOLS"
add_port_option "[x] HTTP"
add_port_option "[ ] HTTP_ADDITION"
add_port_option "[ ] HTTP_AUTH_REQ"
add_port_option "[x] HTTP_CACHE"
add_port_option "[x] HTTP_DAV"
add_port_option "[ ] HTTP_FLV"
add_port_option "[ ] HTTP_GEOIP"
add_port_option "[ ] HTTP_GZIP_STATIC"
add_port_option "[ ] HTTP_GUNZIP_FILTER"
add_port_option "[ ] HTTP_IMAGE_FILTER"
add_port_option "[ ] HTTP_MP4"
add_port_option "[ ] HTTP_PERL"
add_port_option "[ ] HTTP_RANDOM_INDEX"
add_port_option "[ ] HTTP_REALIP"
add_port_option "[x] HTTP_REWRITE"
add_port_option "[ ] HTTP_SECURE_LINK"
add_port_option "[ ] HTTP_SLICE"
add_port_option "[ ] HTTP_SSL"
add_port_option "[x] HTTP_STATUS"
add_port_option "[ ] HTTP_SUB"
add_port_option "[ ] HTTP_XSLT"
add_port_option "[ ] MAIL"
add_port_option "[ ] MAIL_IMAP"
add_port_option "[ ] MAIL_POP3"
add_port_option "[ ] MAIL_SMTP"
add_port_option "[ ] MAIL_SSL"
add_port_option "[ ] HTTPV2"
add_port_option "[ ] NJS"
add_port_option "[ ] STREAM"
add_port_option "[ ] STREAM_SSL"
add_port_option "[ ] STREAM_SSL_PREREAD"
add_port_option "[ ] THREADS"
add_port_option "[x] WWW"
add_port_option "[ ] AJP"
add_port_option "[ ] AWS_AUTH"
add_port_option "[ ] CACHE_PURGE"
add_port_option "[ ] CLOJURE"
add_port_option "[ ] CT"
add_port_option "[ ] ECHO"
add_port_option "[ ] FASTDFS"
add_port_option "[ ] HEADERS_MORE"
add_port_option "[ ] HTTP_ACCEPT_LANGUAGE"
add_port_option "[ ] HTTP_ACCESSKEY"
add_port_option "[ ] HTTP_AUTH_DIGEST"
add_port_option "[ ] HTTP_AUTH_KRB5"
add_port_option "[ ] HTTP_AUTH_LDAP"
add_port_option "[ ] HTTP_AUTH_PAM"
add_port_option "[ ] HTTP_DAV_EXT"
add_port_option "[ ] HTTP_EVAL"
add_port_option "[ ] HTTP_FANCYINDEX"
add_port_option "[ ] HTTP_FOOTER"
add_port_option "[ ] HTTP_GEOIP2"
add_port_option "[ ] HTTP_JSON_STATUS"
add_port_option "[ ] HTTP_MOGILEFS"
add_port_option "[ ] HTTP_MP4_H264"
add_port_option "[ ] HTTP_NOTICE"
add_port_option "[ ] HTTP_PUSH"
add_port_option "[ ] HTTP_PUSH_STREAM"
add_port_option "[ ] HTTP_REDIS"
add_port_option "[ ] HTTP_RESPONSE"
add_port_option "[ ] HTTP_SUBS_FILTER"
add_port_option "[ ] HTTP_TARANTOOL"
add_port_option "[ ] HTTP_UPLOAD"
add_port_option "[ ] HTTP_UPLOAD_PROGRESS"
add_port_option "[ ] HTTP_UPSTREAM_CHECK"
add_port_option "[ ] HTTP_UPSTREAM_FAIR"
add_port_option "[ ] HTTP_UPSTREAM_STICKY"
add_port_option "[ ] HTTP_VIDEO_THUMBEXTRACTOR"
add_port_option "[ ] HTTP_ZIP"
add_port_option "[ ] ARRAYVAR"
add_port_option "[ ] BROTLI"
add_port_option "[ ] DRIZZLE"
add_port_option "[ ] DYNAMIC_UPSTREAM"
add_port_option "[ ] ENCRYPTSESSION"
add_port_option "[ ] FORMINPUT"
add_port_option "[ ] GRIDFS"
add_port_option "[ ] ICONV"
add_port_option "[ ] LET"
add_port_option "[ ] LUA"
add_port_option "[ ] MEMC"
add_port_option "[ ] MODSECURITY"
add_port_option "[ ] MODSECURITY_DEVEL"
add_port_option "[ ] NAXSI"
add_port_option "[ ] PASSENGER"
add_port_option "[ ] POSTGRES"
add_port_option "[ ] RDS_CSV"
add_port_option "[ ] RDS_JSON"
add_port_option "[ ] REDIS2"
add_port_option "[ ] RTMP"
add_port_option "[ ] SET_MISC"
add_port_option "[ ] SFLOW"
add_port_option "[ ] SHIBBOLETH"
add_port_option "[ ] SLOWFS_CACHE"
add_port_option "[ ] SMALL_LIGHT"
add_port_option "[ ] SRCACHE"
add_port_option "[ ] STATSD"
add_port_option "[ ] UDPLOG"
add_port_option "[ ] X11"
add_port_option "[ ] XRID_HEADER"
add_port_option "[ ] XSS"
create_port_options


init_port_options "www_qt4-webkit" "qt4-webkit" "4.8.7_1"
add_port_option "[x] GSTREAMER"
create_port_options


init_port_options "www_qt5-webkit" "qt5-webkit" "5.7.1"
add_port_option "[x] GSTREAMER"
create_port_options


init_port_options "www_qupzilla-qt5" "qupzilla-qt5" "1.8.9_2"
add_port_option "[x] DBUS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] GNOMEKEYRING"
add_port_option "[ ] KWALLET"
create_port_options


init_port_options "www_serf" "serf" "1.3.8_1"
add_port_option "[ ] DOCS"
add_port_option "( ) MIT"
add_port_option "( ) HEIMDAL"
add_port_option "( ) HEIMDAL_BASE"
create_port_options


init_port_options "www_thttpd" "thttpd" "2.27"
add_port_option "[x] FLUSH_LOG"
add_port_option "[ ] HTACCESS"
add_port_option "[ ] INDEXES"
add_port_option "[ ] LOG_UNKNOWN"
add_port_option "[x] REAL_IP"
add_port_option "[x] SENDFILE"
add_port_option "[x] STATS"
create_port_options


init_port_options "www_transmission-web" "transmission-web" "2.80"
add_port_option "[ ] LITE"
create_port_options


init_port_options "www_youtube_dl" "youtube_dl" "2015.01.25"
add_port_option "[ ] BASH"
add_port_option "[ ] FFMPEG"
add_port_option "[ ] FISH"
add_port_option "[ ] RTMPDUMP"
add_port_option "[ ] ZSH"
create_port_options


init_port_options "x11_babl" "babl" "0.1.14"
add_port_option "[ ] SIMD"
create_port_options


init_port_options "x11_keybinder" "keybinder" "0.3.1"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] LUA"
add_port_option "[x] PYTHON"
create_port_options


init_port_options "x11_pixman" "pixman" "0.30.0"
add_port_option "[x] SIMD"
create_port_options


init_port_options "x11_terminator" "terminator" "0.97_1"
add_port_option "[ ] GCONF"
add_port_option "[ ] NLS"
create_port_options


init_port_options "x11_xkeyboard-config" "xkeyboard-config" "2.9_1"
add_port_option "[ ] ETERSOFT"
create_port_options


init_port_options "x11_xterm" "xterm" "325"
add_port_option "[x] 256COLOR"
add_port_option "[ ] DABBREV"
add_port_option "[ ] DECTERM"
add_port_option "[ ] GNOME"
add_port_option "[ ] LOGGING"
add_port_option "[ ] LUIT"
add_port_option "[ ] PCRE"
add_port_option "[ ] REGIS"
add_port_option "[ ] SCRNDUMP"
add_port_option "[ ] SIXEL"
add_port_option "[x] WCHAR"
add_port_option "[ ] XINERAMA"
add_port_option "( ) XAW3D"
add_port_option "( ) XAW3DXFT"
add_port_option "( ) NEXTAW"
create_port_options


init_port_options "x11-fonts_dejavu" "dejavu" "2.33"
add_port_option "[ ] DOCS"
add_port_option "[ ] LINKS"
create_port_options


init_port_options "x11-fonts_fontconfig" "fontconfig" "2.12.1,1"
add_port_option "[ ] DOCS"
add_port_option "( ) HINTING_NONE"
add_port_option "(*) HINTING_SLIGHT"
add_port_option "( ) HINTING_MEDIUM"
add_port_option "( ) HINTING_FULL"
create_port_options


init_port_options "x11-servers_xorg-server" "xorg-server" "1.7.7_10,1"
add_port_option "[x] AIGLX"
add_port_option "[x] SUID"
add_port_option "( ) HAL"
add_port_option "(*) DEVD"
create_port_options


init_port_options "x11-themes_gtk-engines2" "gtk-engines2" "2.20.2_1"
add_port_option "[ ] ANIMATION"
create_port_options


init_port_options "x11-toolkits_gtk20" "gtk" "2.24.27"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
create_port_options


init_port_options "x11-toolkits_gtk30" "gtk3" "3.16.6"
add_port_option "[x] BROADWAY"
add_port_option "[ ] CLOUDPRINT"
add_port_option "[x] COLORD"
add_port_option "[ ] CUPS"
add_port_option "[ ] DEBUG"
add_port_option "[ ] TYPEAHEAD"
create_port_options


init_port_options "x11-toolkits_pango" "pango" "1.30.1"
add_port_option "[x] X11"
create_port_options


init_port_options "x11-toolkits_py-gtk2" "py27-gtk2" "2.24.0_4"
add_port_option "[ ] DOCS"
add_port_option "[ ] EXAMPLES"
add_port_option "[ ] NUMPY"
create_port_options


init_port_options "x11-toolkits_qt5-widgets" "qt5-widgets" "5.7.1"
add_port_option "[ ] GTK3"
create_port_options


init_port_options "x11-toolkits_wxgtk30" "wx30-gtk2" "3.0.2_5"
add_port_option "[x] GSTREAMER"
add_port_option "[ ] MSPACK"
add_port_option "[ ] NLS"
add_port_option "[ ] WEBKIT"
create_port_options


init_port_options "x11-wm_compton" "compton" "20160907_1"
add_port_option "[x] CONFIG"
add_port_option "[x] DBUS"
add_port_option "[ ] DOCS"
add_port_option "[x] DRM"
add_port_option "[x] OPENGL"
add_port_option "[x] PCRE"
add_port_option "[x] XINERAMA"
create_port_options


init_port_options "x11-wm_openbox" "openbox" "3.5.2_5"
add_port_option "[x] IMLIB"
add_port_option "[ ] NLS"
add_port_option "[x] NOTIFY"
add_port_option "[x] PANGO"
add_port_option "[x] SVG"
create_port_options
