#!/bin/sh

# -- check for root --
if [ "$(id -u)" != "0" ]; then
  echo "pacman.sh: sorry, this must be done as root." 1>&2
  exit 1
fi


# -- pkg list --
pkgs=""
echo -n > /tmp/local_pkg_list
pkgs="${pkgs} bash"
pkgs="${pkgs} binutils"
pkgs="${pkgs} bzip2"
pkgs="${pkgs} coreutils"
pkgs="${pkgs} cryptsetup"
pkgs="${pkgs} dash"
pkgs="${pkgs} device-mapper"
pkgs="${pkgs} diffutils"
pkgs="${pkgs} e2fsprogs"
pkgs="${pkgs} dosfstools"
pkgs="${pkgs} file"
pkgs="${pkgs} filesystem"
pkgs="${pkgs} findutils"
pkgs="${pkgs} gawk"
pkgs="${pkgs} gcc-libs"
pkgs="${pkgs} gdisk"
pkgs="${pkgs} gettext"
pkgs="${pkgs} glibc"
pkgs="${pkgs} grep"
pkgs="${pkgs} gzip"
pkgs="${pkgs} kmod"
pkgs="${pkgs} linux"
pkgs="${pkgs} linux-api-headers"
pkgs="${pkgs} linux-firmware"
pkgs="${pkgs} less"
pkgs="${pkgs} licenses"
pkgs="${pkgs} logrotate"
pkgs="${pkgs} man-db"
pkgs="${pkgs} man-pages"
pkgs="${pkgs} mkinitcpio"
pkgs="${pkgs} pacman"
pkgs="${pkgs} pacman-mirrorlist"
pkgs="${pkgs} parted"
pkgs="${pkgs} gptfdisk"
pkgs="${pkgs} procps-ng"
pkgs="${pkgs} psmisc"
pkgs="${pkgs} sed"
pkgs="${pkgs} shadow"
pkgs="${pkgs} sysfsutils"
pkgs="${pkgs} systemd"
pkgs="${pkgs} tar"
pkgs="${pkgs} tzdata"
pkgs="${pkgs} util-linux"
pkgs="${pkgs} vi"
pkgs="${pkgs} which"
pkgs="${pkgs} refind"
pkgs="${pkgs} sharutils"
pkgs="${pkgs} lsof"
pkgs="${pkgs} pciutils"
pkgs="${pkgs} libusb"
pkgs="${pkgs} usbutils"
pkgs="${pkgs} hdparm"
pkgs="${pkgs} sdparm"
pkgs="${pkgs} sysstat"
pkgs="${pkgs} time"
pkgs="${pkgs} openresolv"
pkgs="${pkgs} inetutils"
pkgs="${pkgs} iputils"
pkgs="${pkgs} iproute2"
pkgs="${pkgs} ethtool"
pkgs="${pkgs} net-tools"
pkgs="${pkgs} ndisc6"
pkgs="${pkgs} traceroute"
pkgs="${pkgs} ipv6calc"
pkgs="${pkgs} ca-certificates"
pkgs="${pkgs} sg3_utils"
pkgs="${pkgs} alsa-utils"
pkgs="${pkgs} alsa-oss"
pkgs="${pkgs} bc"
pkgs="${pkgs} kbd"
pkgs="${pkgs} openssh"
pkgs="${pkgs} rpcbind"
pkgs="${pkgs} nfsidmap"
pkgs="${pkgs} nfs-utils"
pkgs="${pkgs} tcpdump"
pkgs="${pkgs} openbsd-netcat"
pkgs="${pkgs} curl"
pkgs="${pkgs} gcc"
pkgs="${pkgs} make"
pkgs="${pkgs} autoconf"
pkgs="${pkgs} automake"
pkgs="${pkgs} m4"
pkgs="${pkgs} bison"
pkgs="${pkgs} ed"
pkgs="${pkgs} libtool"
pkgs="${pkgs} patch"
pkgs="${pkgs} pkg-config"
pkgs="${pkgs} fakeroot"
pkgs="${pkgs} flex"
pkgs="${pkgs} cmake"
pkgs="${pkgs} meson"
pkgs="${pkgs} gdb"
pkgs="${pkgs} strace"
pkgs="${pkgs} dos2unix"
pkgs="${pkgs} exfatprogs"
pkgs="${pkgs} f2fs-tools"
pkgs="${pkgs} nano"
pkgs="${pkgs} zsh"
pkgs="${pkgs} python"
pkgs="${pkgs} go"
pkgs="${pkgs} tmux"
pkgs="${pkgs} dhcpcd"
pkgs="${pkgs} dmidecode"
pkgs="${pkgs} smartmontools"
pkgs="${pkgs} wget"
pkgs="${pkgs} git"
pkgs="${pkgs} iperf"
pkgs="${pkgs} polkit"
pkgs="${pkgs} seatd"
pkgs="${pkgs} ttf-liberation"
pkgs="${pkgs} ttf-dejavu"
pkgs="${pkgs} ttf-caladea"
pkgs="${pkgs} ttf-carlito"
pkgs="${pkgs} ttf-croscore"
pkgs="${pkgs} ttf-junicode"
ls /mnt/var/cache/pacman/AUR_pkg/culmus-*.pkg.tar.* | grep -v -- -debug- >> /tmp/local_pkg_list || exit 1
pkgs="${pkgs} hicolor-icon-theme"
pkgs="${pkgs} mesa-demos"
pkgs="${pkgs} mesa-utils"
pkgs="${pkgs} xf86-input-libinput"
pkgs="${pkgs} xorg-server"
pkgs="${pkgs} xorg-xinit"
pkgs="${pkgs} xorg-xkbutils"
pkgs="${pkgs} libxkbcommon-x11"
pkgs="${pkgs} xorg-xbacklight"
pkgs="${pkgs} xorg-xhost"
pkgs="${pkgs} xorg-xinput"
pkgs="${pkgs} xorg-xrandr"
pkgs="${pkgs} xorg-xset"
pkgs="${pkgs} xorg-xdpyinfo"
pkgs="${pkgs} xorg-xdriinfo"
pkgs="${pkgs} xorg-xev"
pkgs="${pkgs} xorg-xprop"
pkgs="${pkgs} xorg-xvinfo"
pkgs="${pkgs} xorg-xwininfo"
pkgs="${pkgs} xorg-xwayland"
pkgs="${pkgs} xterm"
pkgs="${pkgs} libnotify"
pkgs="${pkgs} picom"
pkgs="${pkgs} hsetroot"
pkgs="${pkgs} adwaita-icon-theme"
pkgs="${pkgs} adwaita-icon-theme-legacy"
pkgs="${pkgs} oxygen-icons"
pkgs="${pkgs} qt5-wayland"
pkgs="${pkgs} qt6-wayland"
pkgs="${pkgs} qt5ct"
pkgs="${pkgs} qt6ct"
pkgs="${pkgs} openbox"
# pkgs="${pkgs} obconf"
pkgs="${pkgs} obconf-qt"
pkgs="${pkgs} tint2"
pkgs="${pkgs} gsimplecal"
pkgs="${pkgs} lxqt-notificationd"
ls /mnt/var/cache/pacman/AUR_pkg/wf-config-*.pkg.tar.* | grep -v -- -debug- >> /tmp/local_pkg_list || exit 1
ls /mnt/var/cache/pacman/AUR_pkg/wayfire-*.pkg.tar.* | grep -v -- -debug- >> /tmp/local_pkg_list || exit 1
ls /mnt/var/cache/pacman/AUR_pkg/wf-shell-*.pkg.tar.* | grep -v -- -debug- >> /tmp/local_pkg_list || exit 1
ls /mnt/var/cache/pacman/AUR_pkg/labwc-*.pkg.tar.* | grep -v -- -debug- >> /tmp/local_pkg_list || exit 1
pkgs="${pkgs} wlr-randr"
pkgs="${pkgs} swaybg"
pkgs="${pkgs} mako"
pkgs="${pkgs} terminator"
pkgs="${pkgs} gmrun"
pkgs="${pkgs} pcmanfm-qt"
pkgs="${pkgs} featherpad"
pkgs="${pkgs} xed"
pkgs="${pkgs} lxtask-gtk3"
pkgs="${pkgs} meld"
pkgs="${pkgs} geany"
pkgs="${pkgs} gtk3-demos"
pkgs="${pkgs} gtk4-demos"
pkgs="${pkgs} libadwaita-demos"


# -- install --
pacman --root /mnt --dbpath /mnt/usr/db/pacman --cachedir /mnt/var/cache/pacman/pkg -Sy || exit 1
pacman --root /mnt --dbpath /mnt/usr/db/pacman --cachedir /mnt/var/cache/pacman/pkg -S ${pkgs} || exit 1

if [ -s /tmp/local_pkg_list ]; then
  cat /tmp/local_pkg_list | pacman -U --root /mnt --dbpath /mnt/usr/db/pacman - || exit 1
fi
